Repository snorose/snorose-front-react, pull requests merged in 2024-12, with the labels that each got.

#745 #743 [FEAT] 베숙트 화면 구성하기
  src/apis/besookt.js
  src/apis/index.js
  src/apis/post.js
  src/components/Carousel/Carousel/Carousel.jsx
  src/components/MainPageListItem/MainPageListItem.jsx
  src/constants/boardMenus.js
  src/constants/reactQuery.js
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.jsx
  src/pages/MainPage/MainPage.jsx
  src/route.js
  src/utils/getBoardTextId.js
Labels: ✨ Feature

#747 #746 [CHORE] 팝업 공지에서 신규 모집 리자 내용 삭제
  src/components/PopUp/PopUp.jsx
  src/components/PopUp/PopUp.module.css
  src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.jsx
Labels: 🧹 Chore

#755 #754 [FIX] 홈화면 배너와 사이드바 겹침 이슈 해결을 위해 사이드바 z-index를 10으로 수정
  src/components/Sidebar/Sidebar/Sidebar.module.css
Labels: 🔧 Fix

#756 Release 20241204
  src/components/Sidebar/Sidebar/Sidebar.module.css
Labels: ❄️ Release

#765 #764 [CHORE] description meta 데이터를 스노로즈 설명글로 업데이트
  public/index.html
Labels: 🧹 Chore

#767 #766 [FEAT] 로그아웃 API 연결
  src/apis/account.js
  src/apis/index.js
  src/hooks/useAuth.js
Labels: 📬 API

#763 #758 [PERF] 메인 페이지 성능 개선
  package-lock.json
  package.json
  public/fonts/SpoqaHanSansNeo-Bold.woff2
  public/fonts/SpoqaHanSansNeo-Medium.woff2
  public/fonts/SpoqaHanSansNeo-Regular.woff2
  public/index.html
  src/App.jsx
  src/assets/fonts/fonts.css
  src/components/Card/Card.jsx
  src/components/Card/Card.module.css
  src/components/Carousel/Slide/Slide.jsx
  src/components/Carousel/Slide/Slide.module.css
  src/index.css
  src/pages/LoginPage/LoginPage/LoginPage.module.css
  src/pages/UnderConstructionPage/UnderConstructionPage.jsx
  src/pages/UnderConstructionPage/UnderConstructionPage.module.css
  src/route.js
Labels: ⚡️ Performance

#769 #768 [CHORE] 팝업 공지에서 리뉴얼 만족도 조사 안내 삭제
  src/components/PopUp/Component.jsx
  src/components/PopUp/Component.module.css
  src/components/PopUp/PopUp.jsx
  src/components/PopUp/PopUp.module.css
Labels: 🧹 Chore

#772 #771 [FIX] ENUM 중 FLOODING 대소문자 수정
  src/constants/point.js
Labels: 🔧 Fix

#770 Release 20241216
  package-lock.json
  package.json
  public/fonts/SpoqaHanSansNeo-Bold.woff2
  public/fonts/SpoqaHanSansNeo-Medium.woff2
  public/fonts/SpoqaHanSansNeo-Regular.woff2
  public/index.html
  public/logos/snoroseLogo120.png
  public/logos/snoroseLogo152.png
  public/logos/snoroseLogo167.png
  public/logos/snoroseLogo180.png
  public/manifest.json
  src/App.jsx
  src/apis/account.js
  src/apis/index.js
  src/assets/fonts/fonts.css
  src/components/Card/Card.jsx
  src/components/Card/Card.module.css
  src/components/Carousel/Slide/Slide.jsx
  src/components/Carousel/Slide/Slide.module.css
  src/components/PopUp/Component.jsx
  src/components/PopUp/Component.module.css
  src/components/PopUp/PopUp.jsx
  src/components/PopUp/PopUp.module.css
  src/constants/point.js
  src/hooks/useAuth.js
  src/index.css
  src/pages/LoginPage/LoginPage/LoginPage.module.css
  src/pages/UnderConstructionPage/UnderConstructionPage.jsx
  src/pages/UnderConstructionPage/UnderConstructionPage.module.css
  src/route.js
Labels: ❄️ Release

#774 #773 [CHORE] 팝업 공지 내용 업데이트 - 241219
  src/components/PopUp/PopUp.jsx
  src/components/PopUp/PopUp.module.css
Labels: 🧹 Chore

#776 #775 [CHORE] 시험후기 업로드 허용 기간 변경
  src/components/Route/CheckExamPeriodRoute.jsx
Labels: 🧹 Chore

#783 #782 [FIX] 시험후기 api 요청 시 수정 데이터를 param이 아니라 request body로 전달하도록 수정
  src/apis/examReview.js
Labels: 🐞 BugFix

#778 #759 [FIX] 특수문자 뒤로 하이퍼링크가 끊기는 문제 수정
  src/components/Url/Url.jsx
  src/components/Url/Url.module.css
  src/components/Url/index.js
  src/pages/PostPage/PostPage/PostContent.jsx
  src/pages/PostPage/PostPage/PostContent.module.css
  src/utils/index.js
  src/utils/link.js
Labels: 🐞 BugFix
