Repository snorose/snorose-front-react, pull requests merged in 2024-10, with the labels that each got.

#519 #518 [FIX] 두번 스크롤 되는 이슈 수정
  src/App.module.css
  src/index.css
  src/pages/BoardPage/BoardPage/BoardPage.module.css
Labels: 🔧 Fix

#521 #520 [FEAT] 비밀번호 유효성 검사에 띄어쓰기 금지 내용 추가
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
Labels: 🔧 Fix

#523 #522 [FIX] 시험후기 마지막 리스트 아이템이 Navbar에 가려지는 문제 수정
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css
Labels: 🔧 Fix

#525 #524 [MODIFY] 숙명인 인증 인풋 라벨 수정
  src/pages/SnoroseVerifyPage/VerifyPage/VerifyPage.jsx
  src/route.js
Labels: 🪄 Modify

#529 #528 [MODIFY] authAxios 타임아웃 설정 삭제
  src/axios/index.js
Labels: 🪄 Modify

#530 #526 [FIX] commentId set 문제 수정
  src/components/InputBar/InputBar.jsx
  src/contexts/CommentContext.jsx
Labels: 🔧 Fix

#532 #531 [FIX] ReviewDownload 컴포넌트 max-width 지정
  src/components/ReviewDownload/ReviewDownload.jsx
  src/components/ReviewDownload/ReviewDownload.module.css
Labels: 🔧 Fix

#533 #531 [FIX] 출석체크 시 로딩 상태일 때 로딩 UI 노출
  src/pages/AttendancePage/AttendancePage.jsx
  src/pages/AttendancePage/AttendancePage.module.css
Labels: 🔧 Fix

#535 #534 [STYLE] 출석페이지 상단 패딩 삭제
  src/pages/AttendancePage/AttendancePage.module.css
Labels: 🎨 UI, 🔧 Fix

#537 #536 [STYLE] AppBar의 z-index css 삭제
  src/components/AppBar/AppBar/AppBar.module.css
  src/components/AppBar/BackAppBar/BackAppBar.module.css
  src/components/AppBar/CloseAppBar/CloseAppBar.module.css
Labels: 🎨 UI, 🔧 Fix

#539 #538 [FIX] pagination 적용된 페이지에 isFetching일 때 리스트 하단에 FetchLoading 컴포넌트 노출
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
  src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
  src/pages/MyPage/ActivityPage/CommentPage.jsx
  src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/MyPostPage.jsx
  src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/ScrapPage.jsx
  src/pages/MyPage/ViewPointListPage/ViewPointListPage.jsx
Labels: 🔧 Fix

#541 #530 [FEAT] 실 전공 데이터로 변경
  src/constants/majors.js
Labels: ✨ Feature

#545 #544 [FIX] input 태그를 focus시, zoom-in 되는 문제 해결
  public/index.html
Labels: 🔧 Fix

#547 #546 [FIX] 앱바의 z-index 1로 수정
  src/components/AppBar/AppBar/AppBar.module.css
  src/components/AppBar/BackAppBar/BackAppBar.module.css
  src/components/AppBar/CloseAppBar/CloseAppBar.module.css
Labels: 🎨 UI, 🔧 Fix

#549 #548 [FIX] uri에서 .(dot)을 자동으로 제거해서 검색이 안 되는 문제 수정
  src/hooks/useSearch.jsx
  src/pages/BoardPage/BoardPage/BoardPage.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/PostPage/PostSearchPage/PostSearchPage.jsx
  src/route.js
Labels: 🔧 Fix

#551 #550 [MODIFY] 시험후기 리스트 content를 qeustionDetail로 교체
  src/components/PostBar/PostBar.jsx
Labels: 🪄 Modify

#554 #553 [FEAT] 리뉴얼 안내 페이지
  package-lock.json
  package.json
  src/assets/images/symbolWhite50.png
  src/pages/UnderConstructionPage/UnderConstructionPage.jsx
  src/pages/UnderConstructionPage/UnderConstructionPage.module.css
  src/route.js
Labels: ✨ Feature

#555 [MERGE] 리뉴얼 안내 페이지 적용
  package-lock.json
  package.json
  public/index.html
  src/App.module.css
  src/apis/login.js
  src/apis/signUp.js
  src/assets/images/symbolWhite50.png
  src/axios/index.js
  src/components/AppBar/AppBar/AppBar.module.css
  src/components/AppBar/BackAppBar/BackAppBar.module.css
  src/components/AppBar/CloseAppBar/CloseAppBar.module.css
  src/components/Comment/Comment/Comment.jsx
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/components/Input/Input/Input.jsx
  src/components/InputBar/InputBar.jsx
  src/components/Modal/DeleteModal.jsx
  src/components/PostBar/PostBar.jsx
  src/components/ReviewDownload/ReviewDownload.jsx
  src/components/ReviewDownload/ReviewDownload.module.css
  src/constants/majors.js
  src/constants/modalOptions.js
  src/contexts/CommentContext.jsx
  src/hooks/useSearch.jsx
  src/index.css
  src/pages/AttendancePage/AttendancePage.jsx
  src/pages/AttendancePage/AttendancePage.module.css
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardPage/BoardPage.jsx
  src/pages/BoardPage/BoardPage/BoardPage.module.css
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css
  src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
  src/pages/LoginPage/FindIdPage/FindIdPage.jsx
  src/pages/LoginPage/FindIdPage/inputCheck.js
  src/pages/LoginPage/FindPwPage/FindPwPage.jsx
  src/pages/LoginPage/SignUpPage/SignUpPageStages/AuthorizationPage.jsx
  src/pages/MyPage/ActivityPage/CommentPage.jsx
  src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/MyPostPage.jsx
  src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/ScrapPage.jsx
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
  src/pages/MyPage/EditInfoPage/EditInfoPage.jsx
  src/pages/MyPage/EditInfoPage/EditInfoPage.module.css
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage/MyPage.module.css
  src/pages/MyPage/MyPage/PolicyTab.jsx
  src/pages/MyPage/PolicyPage/PrivacyPolicyPage.jsx
  src/pages/MyPage/ViewPointListPage/ViewPointListPage.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostSearchPage/PostSearchPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
  src/pages/SnoroseVerifyPage/VerifyPage/VerifyPage.jsx
  src/pages/UnderConstructionPage/UnderConstructionPage.jsx
  src/pages/UnderConstructionPage/UnderConstructionPage.module.css
  src/route.js
Labels: 🌏 Deploy

#556 #553 [FIX] NotFoundPage 라우트 주석 되돌리기
  src/route.js
Labels: 🔧 Fix

#557 [MERGE] NotFoundPage 라우트 주석 되돌리기
  src/route.js
Labels: 🌏 Deploy

#559 #558 [CHORE] route.js 주석 되돌리기
  src/route.js
Labels: ⚙️ Setting

#561 #552 [FIX] 게시글 등록/수정/삭제 더블클릭 방지
  src/pages/BoardPage/BoardPage/BoardPage.module.css
  src/pages/NoticeListPage/NoticeListPage.jsx
  src/pages/NoticeListPage/NoticeListPage.module.css
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.module.css
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostPage/PostPage.module.css
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.module.css
Labels: 🔧 Fix

#563 #562 [FIX] 댓글 신고 시 Input 창에 해당 댓글 들어오는 오류 & 한글 오류 해결
  src/components/Comment/Comment/Comment.jsx
  src/components/InputBar/InputBar.jsx
Labels: 🔧 Fix

#565 #564 [FIX] 루트 경로에서 Navbar가 보이지 않는 문제 수정
  src/route.js
Labels: 🔧 Fix

#567 #566 [FIX] 새로고침을 해야만 포인트가 업데이트되는 이슈 해결
  src/hooks/useAuth.js
  src/hooks/useComment.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
Labels: 🐞 Bug, 🔧 Fix

#571 #568 [FEAT] 유저 신고 기능 구현
  src/constants/modalOptions.js
  src/pages/PostPage/PostPage/PostPage.jsx
Labels: ✨ Feature

#574 [MERGE] 운영 환경에서 서버 동작하는지 확인
  src/components/Comment/Comment/Comment.jsx
  src/components/InputBar/InputBar.jsx
  src/constants/modalOptions.js
  src/hooks/useAuth.js
  src/hooks/useComment.jsx
  src/pages/BoardPage/BoardPage/BoardPage.module.css
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
  src/pages/NoticeListPage/NoticeListPage.jsx
  src/pages/NoticeListPage/NoticeListPage.module.css
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.module.css
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostPage/PostPage.module.css
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.module.css
  src/route.js
Labels: ⚙️ Setting

#576 #575 [CHORE] 운영 브랜치에서 사용할 라우트로 수정
  src/route.js
Labels: ⚙️ Setting

#578 [MERGE] 공사중 페이지로 되돌리기
  src/route.js
Labels: 🌏 Deploy

#579 #560 [FEAT] 배너 클릭 시 연결된 페이지로 랜딩
  src/assets/images/bannerError.jpg
  src/assets/images/bannerError.svg
  src/components/Carousel/Carousel/Carousel.jsx
  src/components/Carousel/Slide/Slide.jsx
  src/components/Carousel/Slide/Slide.module.css
Labels: ✨ Feature

#581 #580 [REFACTOR] 게시글 리스트 컴포넌트로 분리
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
  src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.jsx
  src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.module.css
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
Labels: 🛠️ Refactor

#583 #582 [MODIFY] 시험후기 삭제 후 리스트 페이지에서 FetchLoading 노출
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
Labels: 🪄 Modify

#585 #584 [STYLE] 출석체크 FetchLoading 가운데로 정렬
  src/pages/AttendancePage/AttendancePage.module.css
Labels: 🎨 UI

#587 #586 [STYLE] body의 overflow를 hidden으로 설정
  src/index.css
Labels: 🎨 UI

#589 #588 [STYLE] body의 padding을 0으로 강제
  src/index.css
Labels: 🎨 UI

#592 #590 [MODIFY] 출석 이력 조회, 시험후기 다운로드, 숙명인 인증에 대한 api 요청이 로딩 중일 때 FetchLoading 노출
  src/components/Calendar/Calendar.jsx
  src/components/InputBar/InputBar.module.css
  src/components/Loading/FetchLoadingOverlay.jsx
  src/components/Loading/FetchLoadingOverlay.module.css
  src/components/Loading/index.js
  src/components/ReviewDownload/ReviewDownload.jsx
  src/constants/index.js
  src/constants/loading.js
  src/pages/AttendancePage/AttendancePage.jsx
  src/pages/AttendancePage/AttendancePage.module.css
  src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx
  src/pages/ExamReviewEditPage/ExamReviewEditPage.module.css
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.module.css
  src/pages/SnoroseVerifyPage/VerifyPage/VerifyPage.jsx
Labels: 🪄 Modify

#594 #593 [RENAME] Loading 폴더 구조 변경
  src/components/Loading/FetchLoading/FetchLoading.jsx
  src/components/Loading/FetchLoading/FetchLoading.module.css
  src/components/Loading/FetchLoadingOverlay/FetchLoadingOverlay.jsx
  src/components/Loading/FetchLoadingOverlay/FetchLoadingOverlay.module.css
  src/components/Loading/index.js
Labels: 🛠️ Refactor

#596 #595 [STYLE] DropDownBlue의 z-index 삭제
  src/components/DropDownBlue/DropDownBlue.module.css
Labels: 🎨 UI

#602 #597 [FIX] 공지글 상세페이지로 nav 안 되는 오류, 공지글 등록 안 되는 오류, 게시글 작성/수정에 replace 적용
  src/pages/NoticeListPage/NoticeListPage.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
Labels: 🛠️ Refactor, 🔧 Fix

#605 #569 [FEAT] 개인정보 처리방침 페이지 업데이트
  src/pages/MyPage/PolicyPage/PolicyPage.module.css
  src/pages/MyPage/PolicyPage/PrivacyPolicyPage.jsx
Labels: ✨ Feature

#606 #570 [MODIFY] 닉네임 내 독립적인 자음 허용하도록 유효성 검사 수정
  src/pages/MyPage/EditInfoPage/EditInfoPage.jsx
Labels: 🪄 Modify

#607 #598 [FIX] 사파리에서 svg가 제대로 보이지 않는 이슈 수정
  src/assets/icon.svg
  src/components/AppBar/CloseAppBar/CloseAppBar.jsx
  src/components/Calendar/Calendar.jsx
  src/components/Calendar/Tile/Tile.jsx
  src/components/Comment/Comment/Comment.jsx
  src/components/Comment/NestedComment/NestedComment.jsx
  src/components/DropDownBlue/DropDownBlue.jsx
  src/components/Input/Input/SpecialInput.jsx
  src/components/InputBar/InputBar.jsx
  src/components/InputPassword/InputPassword.jsx
  src/components/Loading/FetchLoading/FetchLoading.jsx
  src/components/PTR/PTR.jsx
  src/components/PostBar/PostBar.jsx
  src/components/ReviewDownload/ReviewDownload.jsx
  src/components/WriteButton/WriteButton.jsx
  src/pages/AlertPage/AlertPage.jsx
  src/pages/AttendancePage/AttendancePage.jsx
  src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.jsx
  src/pages/BoardPage/BoardPage/BoardPage.jsx
  src/pages/BoardPage/BoardPage/BoardPage.module.css
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/LoginPage/FindIdPage/FindIdPage.jsx
  src/pages/LoginPage/FindIdPage/FindIdPage.module.css
  src/pages/LoginPage/FindPwPage/FindPwPage.jsx
  src/pages/LoginPage/FindPwPage/FindPwPage.module.css
  src/pages/LoginPage/FoundIdPage/FoundIdPage.jsx
  src/pages/LoginPage/FoundIdPage/FoundIdPage.module.css
  src/pages/LoginPage/FoundPwPage/FoundPwPage.jsx
  src/pages/LoginPage/FoundPwPage/FoundPwPage.module.css
  src/pages/LoginPage/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage/LoginPage.module.css
  src/pages/LoginPage/NotFoundIdPage/NotFoundIdPage.jsx
  src/pages/LoginPage/NotFoundIdPage/NotFoundIdPage.module.css
  src/pages/LoginPage/NotFoundPwPage/NotFoundPwPage.jsx
  src/pages/LoginPage/NotFoundPwPage/NotFoundPwPage.module.css
  src/pages/LoginPage/SignUpPage/SignUpPage.jsx
  src/pages/LoginPage/SignUpPage/SignUpPageStages/SignUpFailure/SignUpFailurePage.jsx
  src/pages/LoginPage/SignUpPage/SignUpPageStages/SignUpFailure/SignUpFailurePage.module.css
  src/pages/LoginPage/SignUpPage/SignUpSuccessPage/SignUpSuccessPage.jsx
  src/pages/MyPage/EditInfoPage/EditInfoPage.jsx
  src/pages/MyPage/MyPage/ActivityTab.jsx
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage/PolicyTab.jsx
  src/pages/MyPage/ViewPointListPage/ViewPointListPage.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
  src/pages/SnoroseVerifyPage/SnoroseVerifyPage.jsx
  src/pages/UnderConstructionPage/UnderConstructionPage.jsx
Labels: 🎨 UI, 🔧 Fix

#609 #608 [FIX] 사파리에서 BoardBar의 배경 이미지가 보이지 않는 문제 수정
  src/components/BoardBar/BoardBar.jsx
  src/components/BoardBar/BoardBar.module.css
  src/components/BoardCard/BoardCard.module.css
  src/constants/boardMenus.js
  src/pages/BoardPage/BoardPage/BoardPage.jsx
Labels: 🎨 UI, 🔧 Fix

#611 #610 [FEAT] About 스노로즈 페이지 마크업 및 스타일링
  src/assets/icon.svg
  src/assets/images/hallOfFame.svg
  src/components/Accordion/Accordion.jsx
  src/components/Accordion/Accordion.module.css
  src/components/Accordion/AccordionListItem.jsx
  src/components/Accordion/AccordionListItem.module.css
  src/components/Accordion/AccordionTag.jsx
  src/components/Accordion/AccordionTag.module.css
  src/components/Accordion/index.js
  src/constants/about.js
  src/constants/admin.js
  src/constants/index.js
  src/pages/AboutPage/AboutPage.jsx
  src/pages/AboutPage/AboutPage.module.css
Labels: 🎨 UI, ✨ Feature

#613 #612 [REFACTOR] DeleteModal의 primary button 위치를 오른쪽으로 변경
  src/components/Modal/DeleteModal.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
Labels: 🎨 UI, 🛠️ Refactor

#615 #614 [STYLE] BoardCard 폰트 사이즈 키우기
  src/components/BoardCard/BoardCard.module.css
Labels: 🎨 UI

#618 #614 [STYLE] BoardCard padding 수정
  src/components/BoardCard/BoardCard.module.css
Labels: 🎨 UI

#623 #622 [MODIFY] 시험후기 작성 후 상세 페이지로 이동
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
Labels: 🪄 Modify

#625 #624 [ CHORE] About 스노로즈에 누락되었던 map key 추가
  src/components/Accordion/AccordionListItem.jsx
  src/constants/about.js
  src/pages/AboutPage/AboutPage.jsx
Labels: 🪄 Modify

#626 #603 [Feat] 일일 포인트 제한 넘어갈 경우 or 만년설방에 토스트&모달 메시지 다르게 보이도록
  src/constants/modalOptions.js
  src/constants/toast.js
  src/hooks/useComment.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
Labels: ✨ Feature

#630 #629 [FIX] 버튼 한 번 누르면 비활성화하기 & 로딩중 화면 추가
  src/apis/login.js
  src/pages/LoginPage/FindIdPage/FindIdPage.jsx
  src/pages/LoginPage/FindPwPage/FindPwPage.jsx
  src/pages/LoginPage/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage/LoginPage.module.css
Labels: 🔧 Fix

#633 #632 [ FEAT] 시험후기 시험기간이 아닌 경우 메인으로 리다이렉트
  src/components/Route/CheckExamPeriodRoute.jsx
  src/route.js
Labels: ✨ Feature

#635 #634 [MODIFY] 시험후기 상세에 content 내용 추가
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css
Labels: 🪄 Modify

#640 #639 [CHORE] Slide에서 Link를 a 태그로 변경
  src/components/Carousel/Slide/Slide.jsx
Labels: 🧹 Chore

#642 #641 [MODIFY] 아이디 찾기, 비밀번호 찾기에서 상단 앱바의 뒤로가기 버튼 클릭 시 로그인 페이지로 이동하도록 수정
  src/pages/LoginPage/FoundIdPage/FoundIdPage.jsx
  src/pages/LoginPage/FoundPwPage/FoundPwPage.jsx
  src/pages/LoginPage/NotFoundIdPage/NotFoundIdPage.jsx
  src/pages/LoginPage/NotFoundPwPage/NotFoundPwPage.jsx
Labels: 🪄 Modify

#645 #644 [MODIFY] questionDetail을 먼저 검사해서 시험후기 PostBar에서 우선 순위로 노출하도록 변경
  src/components/PostBar/PostBar.jsx
Labels: 🪄 Modify

#648 #643 [FEAT] 서비스 이용 약관 및 footer 수정
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/pages/MyPage/PolicyPage/PolicyPage.module.css
  src/pages/MyPage/PolicyPage/PrivacyPolicyPage.jsx
  src/pages/MyPage/PolicyPage/ServicePolicyPage.jsx
Labels: ✨ Feature

#651 #650 [MODIFY] NoticeBar에서 createAt 변환을 dateFormat으로 변경
  src/components/NoticeBar/NoticeBar.jsx
Labels: 🪄 Modify

#653 #652 [CHORE] ProtectedRoute에서 userInfo가 undefined인 경우 return
  src/ProtectedRoute.jsx
Labels: 🧹 Chore

#654 #649 [FIX] 시험후기 공지글 nav 404 에러 해결 & 텍스트 드래그 방지 처리
  src/constants/boardMenus.js
  src/index.css
  src/pages/NoticeListPage/NoticeListPage.jsx
  src/route.js
Labels: 🔧 Fix

#655 #517 [MODIFY] email 수정
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
Labels: 🪄 Modify

#658 #657 [FIX] exam review edit route
  src/index.css
  src/route.js
Labels: 🔧 Fix

#662 #661 [FIX] ProtectedRoute 로그인 접근 제한 및 애드센스가 자동으로 삽입하는 padding 무시
  src/ProtectedRoute.jsx
  src/index.css
Labels: 🔧 Fix

#663 #646 [CHORE] About 스노로즈에 노션 지원 링크 연결
  src/pages/AboutPage/AboutPage.jsx
Labels: 🧹 Chore

#665 #664 [STYLE] body의 overflow를 hidden으로 변경
  src/index.css
Labels: 🎨 UI

#671 #670 [FIX] 비밀번호 변경 페이지 내 유효성 조건 수정
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
Labels: 🐞 Bug, 🔧 Fix

#675 #674 [FIX] 서버 오류 토스트 추가하기
  src/apis/login.js
  src/apis/signUp.js
  src/pages/LoginPage/FindIdPage/FindIdPage.jsx
  src/pages/LoginPage/FindPwPage/FindPwPage.jsx
  src/pages/LoginPage/SignUpPage/SignUpPageStages/AuthorizationPage.jsx
  src/pages/LoginPage/SignUpPage/SignUpPageStages/UserInfoPage.jsx
Labels: 🔧 Fix

#676 #674 [FIX] 아이디 찾기/비밀번호 찾기에 서버 에러에 대한 토스트 추가
  src/apis/login.js
  src/apis/signUp.js
  src/pages/LoginPage/FindIdPage/FindIdPage.jsx
  src/pages/LoginPage/FindPwPage/FindPwPage.jsx
  src/pages/LoginPage/SignUpPage/SignUpPageStages/AuthorizationPage.jsx
  src/pages/LoginPage/SignUpPage/SignUpPageStages/UserInfoPage.jsx
Labels: 🔧 Fix

#677 #667 [FIX] 인증 페이지 토스트 에러 수정
  src/pages/SnoroseVerifyPage/VerifyPage/VerifyPage.jsx
Labels: 🔧 Fix

#678 #666 [FIX] 댓글 삭제 토스트 에러 수정
  src/hooks/useComment.jsx
Labels: 🔧 Fix

#679 #620 [FEAT] 스크롤 유지 로직 추가
  src/components/PostList/PostList.jsx
  src/hooks/index.js
  src/hooks/useScrollRestoration.js
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
  src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.jsx
  src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css
  src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
  src/pages/MyPage/ActivityPage/ActivityPage.module.css
  src/pages/MyPage/ActivityPage/CommentPage.jsx
  src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/MyPostPage.jsx
  src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/ScrapPage.jsx
  src/pages/NoticeListPage/NoticeListPage.jsx
  src/pages/NoticeListPage/NoticeListPage.module.css
  src/pages/PostPage/PostSearchPage/PostSearchPage.jsx
  src/pages/PostPage/PostSearchPage/PostSearchPage.module.css
Labels: ✨ Feature

#681 [MERGE] 1차 배포 후 버그 수정 사항 반영
  src/ProtectedRoute.jsx
  src/apis/login.js
  src/apis/signUp.js
  src/assets/icon.svg
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/components/PostList/PostList.jsx
  src/hooks/index.js
  src/hooks/useComment.jsx
  src/hooks/useScrollRestoration.js
  src/index.css
  src/pages/AboutPage/AboutPage.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
  src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.jsx
  src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css
  src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
  src/pages/LoginPage/FindIdPage/FindIdPage.jsx
  src/pages/LoginPage/FindIdPage/inputCheck.js
  src/pages/LoginPage/FindPwPage/FindPwPage.jsx
  src/pages/LoginPage/SignUpPage/SignUpPageStages/AccountInfoPage.jsx
  src/pages/LoginPage/SignUpPage/SignUpPageStages/AuthorizationPage.jsx
  src/pages/LoginPage/SignUpPage/SignUpPageStages/UserInfoPage.jsx
  src/pages/MyPage/ActivityPage/ActivityPage.module.css
  src/pages/MyPage/ActivityPage/CommentPage.jsx
  src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/MyPostPage.jsx
  src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/ScrapPage.jsx
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage/MyPage.module.css
  src/pages/NoticeListPage/NoticeListPage.jsx
  src/pages/NoticeListPage/NoticeListPage.module.css
  src/pages/PostPage/PostSearchPage/PostSearchPage.jsx
  src/pages/PostPage/PostSearchPage/PostSearchPage.module.css
  src/pages/SnoroseVerifyPage/VerifyPage/VerifyPage.jsx
Labels: 🌏 Deploy

#684 #682 [PERF] 페이지네이션 API 호출 최적화
  src/components/index.js
  src/constants/reactQuery.js
  src/hooks/usePagination.jsx
  src/hooks/useScrollRestoration.js
  src/hooks/useSearch.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.jsx
  src/pages/BoardPage/index.js
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/CommentPage.jsx
  src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/MyPostPage.jsx
  src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/ScrapPage.jsx
Labels: ⚡️ Performance

#685 #683 [FEAT] 아이디 찾기 내 설명글 추가
  src/pages/LoginPage/FindIdPage/FindIdPage.jsx
  src/pages/LoginPage/FindIdPage/FindIdPage.module.css
  src/pages/LoginPage/FindPwPage/FindPwPage.jsx
  src/pages/LoginPage/FindPwPage/FindPwPage.module.css
Labels: ✨ Feature

#686 Release 20241013 v2
  src/components/index.js
  src/constants/reactQuery.js
  src/hooks/usePagination.jsx
  src/hooks/useScrollRestoration.js
  src/hooks/useSearch.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.jsx
  src/pages/BoardPage/index.js
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/LoginPage/FindIdPage/FindIdPage.jsx
  src/pages/LoginPage/FindIdPage/FindIdPage.module.css
  src/pages/LoginPage/FindPwPage/FindPwPage.jsx
  src/pages/LoginPage/FindPwPage/FindPwPage.module.css
  src/pages/MyPage/ActivityPage/CommentPage.jsx
  src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/MyPostPage.jsx
  src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/ScrapPage.jsx
Labels: ❄️ Release

#688 # 687 [STYLE] 스크롤 영역을 페이지 상위 요소로 변경
  src/components/PostList/PostList.jsx
  src/components/PostList/PostList.module.css
  src/constants/reactQuery.js
  src/hooks/useSearch.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css
  src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
  src/pages/MyPage/ActivityPage/ActivityPage.module.css
  src/pages/NoticeListPage/NoticeListPage.jsx
  src/pages/NoticeListPage/NoticeListPage.module.css
  src/pages/PostPage/PostSearchPage/PostSearchPage.jsx
  src/pages/PostPage/PostSearchPage/PostSearchPage.module.css
Labels: 🎨 UI

#689 #674 [MODIFY] 시험후기 검색 키워드 없어도 필터링 가능하게 변경
  src/apis/search.js
  src/components/DropDownBlue/DropDownBlue.module.css
  src/components/Loading/FetchLoading/FetchLoading.jsx
  src/hooks/useSearch.jsx
  src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css
  src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
Labels: 🪄 Modify

#690 Release 241014
  src/apis/search.js
  src/components/DropDownBlue/DropDownBlue.module.css
  src/components/Loading/FetchLoading/FetchLoading.jsx
  src/components/PostList/PostList.jsx
  src/components/PostList/PostList.module.css
  src/constants/reactQuery.js
  src/hooks/useSearch.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
  src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css
  src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
  src/pages/MyPage/ActivityPage/ActivityPage.module.css
  src/pages/NoticeListPage/NoticeListPage.jsx
  src/pages/NoticeListPage/NoticeListPage.module.css
  src/pages/PostPage/PostSearchPage/PostSearchPage.jsx
  src/pages/PostPage/PostSearchPage/PostSearchPage.module.css
Labels: ❄️ Release

#692 #691 [FIX] 비밀번호 찾기와 아이디 찾기 페이지에서 다음 버튼이 잘 보이게 수정
  src/pages/LoginPage/FindIdPage/FindIdPage.jsx
  src/pages/LoginPage/FindIdPage/FindIdPage.module.css
  src/pages/LoginPage/FindPwPage/FindPwPage.jsx
  src/pages/LoginPage/FindPwPage/FindPwPage.module.css
  src/pages/LoginPage/SignUpPage/SignUpPage.module.css
Labels: 🔧 Fix

#699 #698 [PERF] 페이지네이션 fetch 페이지 수 개선
  src/hooks/usePagination.jsx
Labels: ⚡️ Performance

#700 Release 20241016
  src/components/PopUp/PopUp.jsx
  src/components/PopUp/PopUp.module.css
  src/components/PopUp/index.js
  src/components/index.js
  src/hooks/index.js
  src/hooks/usePagination.jsx
  src/hooks/usePopUp.jsx
  src/index.css
  src/pages/MainPage/MainPage.jsx
  src/utils/date.js
Labels: ❄️ Release

#702 #701 [FIX] 다운로드 된 시험후기 파일명이 잘리는 문제 수정
  src/components/ReviewDownload/ReviewDownload.jsx
Labels: 🔧 Fix

#704 #703 [FIX] 댓글 작성 및 수정에 대한 다중 api 요청 방어
  src/components/InputBar/InputBar.jsx
  src/hooks/useComment.jsx
Labels: 🔧 Fix

#707 #705 [DOCS] 이슈 및 PR 템플릿 수정
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactor-template.md
  .github/pull_request_template.md
Labels: 📄 Docs

#712 #710 [FIX] 게시글 pagination data에서 postId가 중복인 게시글을 걸러냄
  src/components/PostList/PostList.jsx
  src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.jsx
  src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
  src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
  src/pages/MyPage/ActivityPage/CommentPage.jsx
  src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/MyPostPage.jsx
  src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/ScrapPage.jsx
  src/utils/pagination.js
Labels: 🔧 Fix

#714 #708 [DOCS] README.md 리뉴얼
  README.md
Labels: 📄 Docs

#716 #715 [STYLE] 출석체크 캘린더 스타일 수정
  src/components/Calendar/Calendar.style.jsx
  src/index.css
Labels: 🎨 UI

#713 #711 [REFACTOR] 게시글 페이지네이션 데이터 평탄화 로직을 함수로 교체
  src/components/PostList/PostList.jsx
  src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.jsx
  src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
  src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
  src/pages/MyPage/ActivityPage/CommentPage.jsx
  src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/MyPostPage.jsx
  src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/ScrapPage.jsx
Labels: 🛠️ Refactor

#718 #717 [FIX] 시험후기 필터가 사이드바 위로 올라오는 문제 수정
  src/components/DropDownBlue/DropDownBlue.module.css
Labels: 🔧 Fix

#720 #719 [FIX] deduplicatePaginatedData에 대한 중복 import로 인해 발생한 컴파일 에러 문제 수정
  src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
  src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
Labels: 🔧 Fix

#722 #721 [CHORE] 팝업 공지 내용 수정_20241020
  src/components/PopUp/PopUp.jsx
Labels: 🧹 Chore

#723 Release 20241020
  README.md
  src/components/Calendar/Calendar.style.jsx
  src/components/DropDownBlue/DropDownBlue.module.css
  src/components/PopUp/PopUp.jsx
  src/components/PostList/PostList.jsx
  src/index.css
  src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.jsx
  src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
  src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
  src/pages/MyPage/ActivityPage/CommentPage.jsx
  src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/MyPostPage.jsx
  src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/ScrapPage.jsx
  src/utils/pagination.js
Labels: ❄️ Release

#727 #726 [CHORE] ad.txt 파일 추가
  public/ad.txt
Labels: 🧹 Chore

#728 Release 20241023
  public/ad.txt
  src/ProtectedRoute.jsx
  src/components/MainPageListItem/MainPageListItem.jsx
  src/pages/AttendancePage/AttendancePage.jsx
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/ViewPointListPage/ViewPointListPage.jsx
  src/pages/NoticeListPage/NoticeListPage.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
Labels: ❄️ Release

#730 #729 [FEAT] 게시글 내부에 있는 URL을 하이퍼링크로 인식
  src/pages/PostPage/PostPage/PostContent.jsx
  src/pages/PostPage/PostPage/PostContent.module.css
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostPage/PostPage.module.css
  src/pages/PostPage/index.js
Labels: ✨ Feature

#731 Release 20241026
  src/pages/PostPage/PostPage/PostContent.jsx
  src/pages/PostPage/PostPage/PostContent.module.css
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostPage/PostPage.module.css
  src/pages/PostPage/index.js
Labels: ❄️ Release

#733 #732 [FIX] URL 바로 뒤에 오는 문자들도 하이퍼링크로 인식하는 버그 수정
  src/pages/PostPage/PostPage/PostContent.jsx
Labels: 🔧 Fix
