Repository snorose/snorose-front-react, pull requests merged in 2024-07, with the labels that each got.

#10 #9 [FEAT] 하단 Navbar
  package.json
  src/App.jsx
  src/App.module.css
  src/assets/icon.svg
  src/components/Icon/Icon.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/Navbar.module.css
  src/constants/index.js
  src/constants/menus.js
  src/index.css
  src/index.js
  src/pages/BoardPage/BoardPage.jsx
  src/pages/ErrorPage/ErrorPage.jsx
  src/pages/ErrorPage/ErrorPage.module.css
  src/pages/ExamReviewPage/ExamReviewPage.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/NotificationPage/NotificationPage.jsx
  yarn.lock
Labels: ✨ Feature

#13 #12 [FIX] /에 있을 때 하단 Navbar에서 홈메뉴가 활성화되지 않는 문제 해결
  src/components/Navbar/Navbar.jsx
Labels: 🐞 Bug

#17 #16 [FEAT] 좌측 Sidebar
  src/assets/icon.svg
  src/components/Navbar/Navbar.jsx
  src/components/Sidebar/List/List.jsx
  src/components/Sidebar/List/List.module.css
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/Sidebar.module.css
  src/constants/index.js
  src/constants/menus.js
  src/index.js
  src/pages/AboutPage/AboutPage.jsx
  src/pages/AlertPage/AlertPage.jsx
  src/pages/AuthPage/AuthPage.jsx
  src/pages/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardPage.jsx
  src/pages/HelpPage/HelpPage.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/NoticePage/NoticePage.jsx
Labels: ✨ Feature

#20 #18 [FEAT] 비밀번호 수정 페이지 view 구현
  src/assets/icon-arrow-back.svg
  src/assets/icon-eye.svg
  src/index.js
  src/pages/MyPage/ChangePassword.jsx
  src/pages/MyPage/ChangePassword.module.css
Labels: ✨ Feature

#22 #18 [FEAT] 내 정보 수정 페이지 view 구현
  src/assets/icon-calendar.svg
  src/assets/icon-profile.svg
  src/index.js
  src/pages/MyPage/EditInfoPage.jsx
  src/pages/MyPage/EditInfoPage.module.css
Labels: ✨ Feature

#29 #27 [DOCS] Update README.md
  README.md
Labels: 📄 Docs

#34 #33 [FEAT] 회원 탈퇴 페이지 view 구현
  src/assets/icon.svg
  src/index.js
  src/pages/MyPage/ChangePassword.module.css
  src/pages/MyPage/DeleteAccountPage.jsx
  src/pages/MyPage/DeleteAccountPage.module.css
  src/pages/MyPage/EditInfoPage.module.css
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.module.css
Labels: ✨ Feature

#35 #25 [FEAT] PostPage 기초 구현 및 스타일링 ✨
  package-lock.json
  package.json
  src/assets/icon.svg
  src/components/Commnet/Comment.jsx
  src/components/Commnet/Comment.module.css
  src/components/Commnet/NestedComment.jsx
  src/components/InputBar/InputBar.jsx
  src/components/InputBar/InputBar.module.css
  src/components/PTR/PTR.jsx
  src/components/PostBar/PostBar.jsx
  src/constants/boardmenus.js
  src/constants/commentDummy.js
  src/constants/postCategories.js
  src/constants/postContentDummy.js
  src/constants/postListDummy.js
  src/index.js
  src/pages/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
  src/pages/BoardPage/BoardPage/BoardPage.jsx
  src/pages/BoardPage/BoardPage/BoardPage.module.css
  src/pages/BoardPage/index.js
  src/pages/PostListPage/PostListPage.jsx
  src/pages/PostListPage/PostListPage.module.css
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostPage/PostPage.module.css
  src/pages/PostPage/PostSearchPage/PostSearchPage.jsx
  src/pages/PostPage/PostSearchPage/PostSearchPage.module.css
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.module.css
  src/pages/PostPage/index.js
  src/utils/timeAgo.js
Labels: ✨ Feature

#36 #33 [FEAT] 보유 포인트 보기 view 구현
  src/assets/icon.svg
  src/index.js
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/ViewPointListPage.jsx
  src/pages/MyPage/ViewPointListPage.module.css
Labels: ✨ Feature

#42 #18 [MODIFY] 탈퇴 페이지 UI 변경
  src/pages/MyPage/DeleteAccountPage.jsx
  src/pages/MyPage/DeleteAccountPage.module.css
  src/pages/MyPage/MyPage.jsx
Labels: 🎨 UI

#40 #18 [MODIFY] 내 정보 수정 페이지 UI 변경
  src/assets/icon-calendar.svg
  src/assets/icon.svg
  src/index.js
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.module.css
  src/pages/MyPage/DeleteAccountPage/DeleteAccountPage.jsx
  src/pages/MyPage/DeleteAccountPage/DeleteAccountPage.module.css
  src/pages/MyPage/EditInfoPage.jsx
  src/pages/MyPage/EditInfoPage.module.css
  src/pages/MyPage/EditInfoPage/EditInfoPage.jsx
  src/pages/MyPage/EditInfoPage/EditInfoPage.module.css
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage/MyPage.module.css
  src/pages/MyPage/index.js
  yarn.lock
Labels: 🎨 UI

#46 #43 [STYLE] Navbar 컴포넌트에 새로운 디자인 적용
  src/assets/icon.svg
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/Navbar.module.css
  src/constants/menus.js
  src/pages/BoardPage/BoardPage/BoardPage.jsx
Labels: 🎨 UI

#47 #44 [STYLE] Sidebar 컴포넌트에 새로운 디자인 적용
  src/components/Navbar/Navbar.module.css
  src/components/Sidebar/List/List.jsx
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/Sidebar.module.css
  src/constants/menus.js
Labels: 🎨 UI

#57 #56 [FIX] BoardCard 컴포넌트의 svg Cannot find module 에러 해결
  src/components/BoardCard/BoardCard.jsx
Labels: 🔧 Fix

#59 #58 [DOCS] Bug report 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: 📄 Docs

#55 #54 [FEAT] Toast 개발
  public/index.html
  src/components/Toast/Toast.jsx
  src/components/Toast/Toast.module.css
  src/constants/index.js
  src/constants/toast.js
  src/contexts/ToastContext.jsx
  src/hooks/useToast.jsx
  src/index.css
  src/index.js
Labels: ✨ Feature

#51 #32 [FEAT] 아이디 찾기 페이지 구현
  package.json
  src/App.jsx
  src/assets/Union.svg
  src/assets/icon.svg
  src/components/Input/Input.jsx
  src/components/Input/Input.module.css
  src/components/Submit/Submit.jsx
  src/components/Submit/Submit.module.css
  src/constants/menuWithoutNav.js
  src/index.js
  src/pages/LoginPage/FindIdPage/FindIdPage.jsx
  src/pages/LoginPage/FindIdPage/FindIdPage.module.css
  src/pages/LoginPage/FindIdPage/inputCheck.js
  src/pages/LoginPage/FoundIdPage/FoundIdPage.jsx
  src/pages/LoginPage/FoundIdPage/FoundIdPage.module.css
  src/pages/LoginPage/Login.jsx
  src/pages/LoginPage/NotFoundIdPage/NotFoundIdPage.jsx
  src/pages/LoginPage/NotFoundIdPage/NotFoundIdPage.module.css
  yarn.lock
Labels: ✨ Feature

#63 #62 [FEAT] CloseAppBar
  src/assets/icon.svg
  src/components/AppBar/ActionButton/ActionButton.jsx
  src/components/AppBar/ActionButton/ActionButton.module.css
  src/components/AppBar/CloseAppBar/CloseAppBar.jsx
  src/components/AppBar/CloseAppBar/CloseAppBar.module.css
Labels: ✨ Feature

#66 #48 [FEAT] 게시판 리스트 새 디자인으로 수정
  src/components/BoardBar/BoardBar.jsx
  src/components/BoardHeader/BoardHeader.jsx
  src/components/BoardHeader/BoardHeader.module.css
  src/components/PTR/PTR.jsx
  src/components/PTR/PTR.module.css
  src/components/PostBar/PostBar.jsx
  src/components/PostBar/PostBar.module.css
  src/components/Sponser/Sponser.jsx
  src/constants/boardMenus.js
  src/constants/postListDummy.js
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
Labels: 🎨 UI

#61 #60 [FEAT] BackAppBar
  src/assets/icon.svg
  src/components/BackAppBar/BackAppBar.jsx
  src/components/BackAppBar/BackAppBar.module.css
  src/components/Header/Header.jsx
  src/components/MenuIcon/MenuIcon.jsx
  src/components/Search/Search.jsx
  src/components/Search/Search.module.css
  src/components/Sidebar/Sidebar.module.css
  src/constants/index.js
  src/constants/search.js
  src/index.js
  src/pages/SearchPage/SearchPage.jsx
Labels: ✨ Feature
