Repository snorose/snorose-front-react, pull requests merged in 2024-09, with the labels that each got.

#252 #251 [STYLE] 내가 쓴 공지가 아니면, 공지글에 dot3 버튼 안 띄우도록
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
Labels: 🎨 UI

#254 #253 [STYLE] InputBar에 textAreaAutosize 설정 (5줄까지 보여주고 그 후론 스크롤 생김)
  src/components/InputBar/InputBar.jsx
  src/components/InputBar/InputBar.module.css
Labels: 🎨 UI

#258 #257 [FIX] 댓글 필터링 로직 수정 & 댓글 수 오류 해결
  src/components/Comment/CommentList/CommentList.jsx
  src/components/InputBar/InputBar.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/utils/filterComment.js
Labels: 🔧 Fix

#265 #264 [FEAT] 버튼에 cursor:pointer 설정 & 게시글 댓글 아이콘에는 hover 액션 안 되도록 설정
  src/components/AppBar/CloseAppBar/CloseAppBar.module.css
  src/components/Comment/Comment/Comment.module.css
  src/components/DropDownMenu/DropDownMenu.module.css
  src/components/NoticeBar/NoticeBar.module.css
  src/components/PostBar/PostBar.module.css
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css
  src/pages/PostPage/PostPage/PostPage.module.css
  src/pages/PostPage/PostWritePage/PostWritePage.module.css
Labels: ✨ Feature

#263 #262 [FIX] 전체 게시판 검색에서 PostBar 클릭 시 nav 안 되는 오류 수정
  src/components/PostBar/PostBar.jsx
Labels: 🔧 Fix

#267 #261 [MODIFY] 내가 작성한 댓글은 수정/삭제 모달, 다른 사람이 작성한 댓글은 신고 모달 보이게 변경
  src/components/Comment/Comment/Comment.jsx
  src/components/Comment/Comment/Comment.module.css
  src/components/Comment/NestedComment/NestedComment.jsx
  src/components/InputBar/InputBar.jsx
  src/components/Modal/DeleteModal.jsx
  src/components/Modal/Options.jsx
  src/contexts/CommentContext.jsx
Labels: 🪄 Modify

#269 #268 [MODIFY] 시험후기 페이지 questionDetail 필수 입력으로 변경
  src/components/AppBar/CloseAppBar/CloseAppBar.jsx
  src/components/Toast/Toast.jsx
  src/constants/toast.js
  src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
Labels: 🪄 Modify

#271 #270 [MODIFY] 시험후기 상세에서 isWriter에 따라 수정/삭제 또는 신고 모달이 보여지게 수정
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css
Labels: 🪄 Modify

#272 #260 [FEAT] 숙명 포털 인증 신청 API 연결
  src/apis/banner.js
  src/apis/index.js
  src/apis/verify.js
  src/axios/index.js
  src/components/Icon/Icon.jsx
  src/constants/toast.js
  src/pages/MainPage/MainPage.jsx
  src/pages/SnoroseVerifyPage/Input/Input.jsx
  src/pages/SnoroseVerifyPage/Input/Input.module.css
  src/pages/SnoroseVerifyPage/VerifyPage/VerifyPage.jsx
  src/utils/index.js
  src/utils/validate.js
Labels: 📬 API

#280 #208 [MODIFY] 글이 없을 경우 나타나는 일러스트 이미지 변경
  src/pages/MyPage/ActivityPage/ActivityPage.module.css
  src/pages/MyPage/ActivityPage/CommentPage.jsx
  src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/MyPostPage.jsx
  src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/ScrapPage.jsx
Labels: 🎨 UI

#276 #275 [MODIFY] 해당 월의 첫 출석인지 아닌지에 따라 다른 메시지 노출
  src/components/Calendar/Calendar.jsx
  src/constants/attendance.js
  src/constants/index.js
  src/pages/AttendancePage/AttendancePage.jsx
Labels: 🔧 Fix, 🪄 Modify

#282 #281 [MODIFY] 시험후기 생성, 삭제 후 포인트 증감 로직 삭제
  src/apis/banner.js
  src/apis/comment.js
  src/apis/examReview.js
  src/apis/like.js
  src/apis/login.js
  src/apis/notice.js
  src/apis/point.js
  src/apis/post.js
  src/apis/search.js
  src/apis/userInfo.js
  src/axios/index.js
  src/components/ReviewDownload/ReviewDownload.jsx
  src/constants/examReview.js
  src/constants/index.js
  src/constants/toast.js
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
Labels: 🪄 Modify

#283 #277 [FEAT] 404 라우트 에러 핸들링
  src/App.jsx
  src/index.js
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/LoginPage/index.js
  src/pages/MyPage/index.js
  src/pages/NotFoundPage/NotFoundPage.jsx
  src/pages/NotFoundPage/NotFoundPage.module.css
  src/pages/NotFoundPage/index.js
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/SnoroseVerifyPage/Button/Button.jsx
  src/route.js
  src/utils/findRoute.js
Labels: ✨ Feature

#285 #284 [MODIFY] 게시글, 댓글 쪽 포인트 로직 삭제
  src/hooks/useComment.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
Labels: 🪄 Modify

#288 #266 [MODIFY] 전체 게시판 검색 / 특정 게시판 검색 / 시험후기 검색 - url쿼리로 검색하도록 검색 로직 수정
  src/components/AppBar/BackAppBar/BackAppBar.jsx
  src/components/PostBar/PostBar.jsx
  src/components/Search/Search.jsx
  src/hooks/useSearch.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
  src/pages/PostPage/PostSearchPage/PostSearchPage.jsx
  src/route.js
  src/utils/debounce.js
  src/utils/index.js
Labels: 🪄 Modify

#287 #286 [MODIFY] 2차 QA 피드백 반영
  src/assets/images/bannerError.jpg
  src/components/Carousel/Carousel/Carousel.jsx
  src/components/Carousel/Carousel/Carousel.module.css
  src/components/Carousel/Slide/Slide.jsx
  src/constants/boardMenus.js
Labels: 🪄 Modify

#279 #278 [FIX] interceptor 사용해서 토큰 실시간 업데이트하기
  src/apis/index.js
  src/apis/login.js
  src/apis/signUp.js
  src/axios/index.js
  src/pages/LoginPage/FindIdPage/inputCheck.js
  src/pages/LoginPage/LoginPage/LoginPage.jsx
  src/pages/LoginPage/SignUpPage/SignUpPageStages/UserInfoPage.jsx
Labels: 🔧 Fix

#293 #292 [FIX] 회원가입 이메일 인증 (차단됨:mixed-content) 오류 해결
  src/pages/LoginPage/SignUpPage/SignUpPageStages/AuthorizationPage.jsx
Labels: 🔧 Fix

#294 [MERGE] 회원가입 이메일 인증 이슈 해결
  src/pages/LoginPage/SignUpPage/SignUpPageStages/AuthorizationPage.jsx
Labels: 🌏 Deploy

#309 [MERGE] 시험후기 스크롤 버그 수정
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css
Labels: 🌏 Deploy

#311 #310 [FEAT] 유저 더미 데이터를 서버 데이터로 교체
  src/ProtectedRoute.jsx
  src/apis/banner.js
  src/components/BoardCard/BoardCard.jsx
  src/components/CategoryBoard/CategoryBoardItem/CategoryBoardItem.jsx
  src/components/CategoryBoard/CategoryBoardItemDetail/CategoryBoardItemDetail.jsx
  src/components/MainPageListItem/MainPageListItem.jsx
  src/components/ReviewDownload/ReviewDownload.jsx
  src/constants/index.js
  src/constants/user.js
  src/pages/AttendancePage/AttendancePage.jsx
  src/pages/AuthPage/AuthPage.jsx
  src/pages/AuthPage/index.js
  src/pages/HelpPage/HelpPage.jsx
  src/pages/HelpPage/index.js
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
  src/route.js
Labels: ✨ Feature

#319 #318 [FIX] 홈 화면에서 로그아웃 버튼 클릭 시 버튼 텍스트가 로그인으로 바뀌도록 수정함
  src/hooks/useAuth.js
Labels: 🔧 Fix

#315 #314 [FEAT] 스노로즈 인증 신청 확정 이용약관으로 교체
  src/constants/verify.js
  src/pages/SnoroseVerifyPage/TermsPage/TermsPage.jsx
  src/pages/SnoroseVerifyPage/TermsPage/TermsPage.module.css
Labels: ✨ Feature

#317 #316 [REFACTOR] 페이지네이션 코드 통일하기
  src/components/PostBar/PostBar.jsx
  src/hooks/index.js
  src/hooks/useIntersect.jsx
  src/hooks/usePagination.jsx
  src/hooks/useSearch.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
  src/pages/BoardPage/BoardPage/BoardPage.jsx
  src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css
  src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
  src/pages/MyPage/ActivityPage/CommentPage.jsx
  src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/MyPostPage.jsx
  src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/ScrapPage.jsx
  src/pages/MyPage/ViewPointListPage/ViewPointListPage.jsx
  src/pages/PostPage/PostSearchPage/PostSearchPage.jsx
  src/pages/PostPage/PostSearchPage/PostSearchPage.module.css
  src/route.js
  src/utils/getBoardTextId.js
Labels: 🛠️ Refactor

#322 #321 [FIX] ProtectedRoute에서 유저 정보 status가 loading일 경우 undefined를 반환하도록 수정
  src/ProtectedRoute.jsx
Labels: 🔧 Fix

#324 #323 [FIX] 로그아웃 시 유저 정보 캐시를 삭제
  src/hooks/useAuth.js
Labels: 🔧 Fix

#327 #326 [FIX] views 클래스로 따로 스타일 지정
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostPage/PostPage.module.css
Labels: 🎨 UI, 🔧 Fix

#328 [MERGE] dev to main
  src/ProtectedRoute.jsx
  src/hooks/useAuth.js
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostPage/PostPage.module.css
Labels: 🌏 Deploy

#330 #329 [FIX] 메인 화면에서 공지글 & 게시글 검색 - 접근 권한 설정
  src/ProtectedRoute.jsx
  src/route.js
Labels: 🔧 Fix

#333 #332 [FEAT] 메인페이지 전체공지 게시판 연결
  src/constants/boardMenus.js
  src/pages/MainPage/MainPage.jsx
  src/route.js
Labels: 📬 API, ✨ Feature

#336 [MERGE] 공지 게시판 & 접근 권한 설정
  src/ProtectedRoute.jsx
  src/constants/boardMenus.js
  src/pages/MainPage/MainPage.jsx
  src/route.js
Labels: 🌏 Deploy

#338 #337 [FIX] 인증된 시험후기는 옵션 모달에서 수정 메뉴 숨김
  src/components/PostBar/PostBar.jsx
  src/components/PostBar/PostBar.module.css
  src/constants/modalOptions.js
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css
Labels: 🔧 Fix

#340 #339 [FIX] 내가 작성했거나 이미 다운로드 받은 후기는 다운로드 확인 모달창을 띄우지 않음
  src/components/ReviewDownload/ReviewDownload.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
Labels: 🔧 Fix

#341 [MERGE] 인증된 시험후기 옵션 모달에서 수정 메뉴 숨김 & 이미 다운로드 받거나 내가 작성한 시험후기는 다운로드 확인 모달창 뜨지 않음
  src/components/PostBar/PostBar.jsx
  src/components/PostBar/PostBar.module.css
  src/components/ReviewDownload/ReviewDownload.jsx
  src/constants/modalOptions.js
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css
Labels: 🌏 Deploy

#343 #342 [FIX] 시험후기 필터 유지되도록 수정
  src/hooks/useSearch.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
Labels: 🔧 Fix

#344 [MERGE] 시험후기 상세에서 리스트로 이동 시 검색 필터 유지
  src/hooks/useSearch.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
Labels: 🔧 Fix

#346 #345 [FIX] 알파 테스트 마이너 이슈 수정
  src/constants/dropDown.js
  src/constants/toast.js
  src/constants/verify.js
Labels: 🔧 Fix

#347 [MERGE] 마이너 이슈 수정
  src/constants/dropDown.js
  src/constants/toast.js
  src/constants/verify.js
Labels: 🌏 Deploy

#349 #348 [REFACTOR] 마이페이지 접근 권한 핸들링 로직을 ProtectedRoute로 교체
  src/hooks/useAuth.js
  src/pages/MyPage/MyPage/MyPage.jsx
  src/route.js
Labels: 🛠️ Refactor

#351 #350 [MODIFY] 시험후기 수강 분반 입력 필드를 텍스트 필드로 변경
  src/components/Fieldset/TextField/TextField.jsx
  src/components/Fieldset/TextField/TextField.module.css
  src/components/Fieldset/index.js
  src/constants/dropDown.js
  src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
  src/utils/index.js
  src/utils/regex.js
Labels: 🪄 Modify

#353 #352 [FIX] 사이드바에 누락된 공지사항 메뉴 추가
  src/constants/menus.js
Labels: 🔧 Fix

#355 #352 [MODIFY] Dropdown 컴포넌트 포커스 상태인 경우 글자색 파란색으로 변경
  src/components/Fieldset/Dropdown/Dropdown.jsx
  src/components/Fieldset/Dropdown/Dropdown.module.css
  src/pages/LoginPage/SignUpPage/SignUpPageStages/UserInfoPage.jsx
Labels: 🪄 Modify

#356 [MERGE] 알파 테스트 이슈 수정
  src/components/Fieldset/Dropdown/Dropdown.jsx
  src/components/Fieldset/Dropdown/Dropdown.module.css
  src/components/Fieldset/TextField/TextField.jsx
  src/components/Fieldset/TextField/TextField.module.css
  src/components/Fieldset/index.js
  src/constants/dropDown.js
  src/constants/menus.js
  src/hooks/useAuth.js
  src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
  src/pages/LoginPage/SignUpPage/SignUpPageStages/UserInfoPage.jsx
  src/pages/MyPage/MyPage/MyPage.jsx
  src/route.js
  src/utils/index.js
  src/utils/regex.js
Labels: 🌏 Deploy

#358 #357 [MODIFY] 숙명인 인증 신청 description 수정
  src/constants/verify.js
  src/pages/SnoroseVerifyPage/SnoroseVerifyPage.module.css
Labels: 🪄 Modify

#335 #325 [FIX] 댓글에 페이지네이션 적용
  src/apis/comment.js
  src/components/Comment/Comment/Comment.jsx
  src/components/Comment/CommentList/CommentList.jsx
  src/hooks/useComment.jsx
  src/hooks/usePagination.jsx
  src/utils/index.js
  src/utils/pagination.js
Labels: 🔧 Fix

#359 [MERGE] 댓글 페이지네이션 적용
  src/apis/comment.js
  src/components/Comment/Comment/Comment.jsx
  src/components/Comment/CommentList/CommentList.jsx
  src/constants/verify.js
  src/hooks/useComment.jsx
  src/hooks/usePagination.jsx
  src/pages/SnoroseVerifyPage/SnoroseVerifyPage.module.css
  src/utils/index.js
  src/utils/pagination.js
Labels: 🌏 Deploy

#366 [MERGE] 시험후기 다운로드 포인트 로직 삭제
  src/apis/banner.js
  src/apis/examReview.js
  src/components/ReviewDownload/ReviewDownload.jsx
Labels: 🌏 Deploy

#368 #367 [FIX] 댓글 페이지네이션 버그 수정
  src/components/Comment/CommentList/CommentList.jsx
  src/components/Loading/FetchLoading.module.css
  src/hooks/useComment.jsx
  src/hooks/usePagination.jsx
Labels: 🔧 Fix

#370 #369 [FIX] 수강후기 작성 - 수강 분반 입력 필드에 조건 검사 추가
  src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
  src/utils/index.js
  src/utils/regex.js
  src/utils/validate.js
Labels: 🔧 Fix

#374 #373 [FIX] 검색 결과 FetchLoading 수정
  src/components/PostBar/PostBar.jsx
  src/components/PostList/PostList.jsx
  src/components/PostList/PostList.module.css
  src/components/PostList/index.js
  src/pages/PostPage/PostSearchPage/PostSearchPage.jsx
Labels: 🔧 Fix

#375 [MERGE] 알파테스트 이슈 수정
  src/components/Comment/CommentList/CommentList.jsx
  src/components/Loading/FetchLoading.module.css
  src/components/PostBar/PostBar.jsx
  src/components/PostList/PostList.jsx
  src/components/PostList/PostList.module.css
  src/components/PostList/index.js
  src/components/ReviewContentItem/ReviewContentItem.jsx
  src/components/ReviewContentItem/ReviewContentItem.module.css
  src/constants/align.js
  src/constants/index.js
  src/hooks/useComment.jsx
  src/hooks/usePagination.jsx
  src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
  src/pages/PostPage/PostSearchPage/PostSearchPage.jsx
  src/utils/index.js
  src/utils/regex.js
  src/utils/validate.js
Labels: 🌏 Deploy

#377 #376 [MODIFY] PC 환경에서만 시험후기 다운로드 완료 토스트 노출
  src/components/ReviewDownload/ReviewDownload.jsx
  src/utils/index.js
  src/utils/window.js
Labels: 🪄 Modify

#378 [MERGE] PC 환경에서만 시험후기 다운로드 완료 토스트 노출
  src/components/ReviewDownload/ReviewDownload.jsx
  src/utils/index.js
  src/utils/window.js
Labels: 🌏 Deploy

#380 #379 [FIX] 다운로드 파일명 뒤에 타임스탬프 추가
  src/components/ReviewDownload/ReviewDownload.jsx
Labels: 🔧 Fix

#381 [MERGE] 시험후기 다운로드 파일명 뒤에 타임스탬프 추가
  src/components/ReviewDownload/ReviewDownload.jsx
Labels: 🌏 Deploy

#383 #382 [MODIFY] 모바일 환경 시험후기 다운로드 완료 토스트 복구
  src/components/ReviewDownload/ReviewDownload.jsx
  src/utils/index.js
  src/utils/window.js
Labels: 🪄 Modify

#384 [MERGE] 모바일 환경 시험후기 다운로드 토스트 복구
  src/components/ReviewDownload/ReviewDownload.jsx
  src/utils/index.js
  src/utils/window.js
Labels: 🌏 Deploy

#386 #334 [FEAT] 메인페이지의 공지사항 게시판 추가 (조회/작성/수정)
  src/components/Card/Card.module.css
  src/constants/boardMenus.js
  src/pages/NoticeListPage/NoticeListPage.jsx
  src/pages/NoticeListPage/NoticeListPage.module.css
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
  src/route.js
Labels: ✨ Feature

#388 #387 [FEAT] 시험후기 공지 게시판 추가
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css
  src/pages/NoticeListPage/NoticeListPage.jsx
  src/route.js
Labels: ✨ Feature

#390 #291 [FEAT] 댓글 신고하기, 게시글 신고하기 기능 구현 및 API 연동
  src/apis/comment.js
  src/apis/post.js
  src/assets/icon.svg
  src/components/Comment/Comment/Comment.jsx
  src/components/Modal/Modal.module.css
  src/components/Modal/OptionModal.jsx
  src/components/Modal/Options.jsx
  src/constants/board.js
  src/constants/modalOptions.js
  src/pages/PostPage/PostPage/PostPage.jsx
Labels: 📬 API, ✨ Feature

#394 #393 [REMOVE] yarn 패키지 매니저 삭제
  .yarnrc.yml
  yarn.lock
Labels: 🔧 Fix

#395 #392 [FIX] 새 비밀번호와 확인을 동일하게 입력하여도, 유효성 검사를 통과하지 못하면 submit 버튼 비활성화되도록 수정
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
  src/pages/MyPage/EditInfoPage/EditInfoPage.jsx
Labels: 🔧 Fix

#397 #396 [FEAT] 마이페이지 내 계정정보 항목에 이름 추가 및 생년월일 형식 변경
  src/pages/MyPage/MyPage/AccountTab.jsx
Labels: 🎨 UI

#398 [MERGE] 게시글, 댓글 신고하기 기능 구현 및 마이페이지에 알파테스트 이슈 반영
  .yarnrc.yml
  src/apis/comment.js
  src/apis/post.js
  src/assets/icon.svg
  src/components/Card/Card.module.css
  src/components/Comment/Comment/Comment.jsx
  src/components/Modal/Modal.module.css
  src/components/Modal/OptionModal.jsx
  src/components/Modal/Options.jsx
  src/constants/board.js
  src/constants/boardMenus.js
  src/constants/modalOptions.js
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
  src/pages/MyPage/EditInfoPage/EditInfoPage.jsx
  src/pages/MyPage/MyPage/AccountTab.jsx
  src/pages/NoticeListPage/NoticeListPage.jsx
  src/pages/NoticeListPage/NoticeListPage.module.css
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
  src/route.js
  yarn.lock
Labels: 🌏 Deploy

#364 #363 [FIX] 비밀번호 찾기 페이지의 아이디 인풋 에러 메세지 고치기
  src/pages/LoginPage/FindIdPage/inputCheck.js
  src/pages/LoginPage/FindPwPage/FindPwPage.jsx
Labels: 🔧 Fix

#399 #389 [FIX] PTR 무한 로딩 & 모든 페이지 refetch 오류 해결
  src/components/PTR/PTR.jsx
  src/components/PTR/PTR.module.css
  src/hooks/usePagination.jsx
  src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
Labels: 🛠️ Refactor, 🔧 Fix

#401 #400 [FIX] 댓글 관련 오류 해결
  src/components/Comment/Comment/Comment.jsx
  src/components/InputBar/InputBar.jsx
  src/contexts/CommentContext.jsx
Labels: 🔧 Fix

#404 #403 [FIX] 에러메세지를 화면에서 띄워주기(알파테스트 이슈 반영)
  src/pages/MyPage/ActivityPage/CommentPage.jsx
  src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/MyPostPage.jsx
  src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/ScrapPage.jsx
Labels: 🔧 Fix

#406 #405 [FEAT] 누락된 POINT_DEDUCTION_ETC enum값 추가
  src/constants/point.js
Labels: ✨ Feature

#409 #408 [FIX] 댓글 수정, 삭제 버그 해결
  src/components/Comment/Comment/Comment.jsx
  src/components/Comment/NestedComment/NestedComment.jsx
  src/components/Modal/DeleteModal.jsx
  src/components/Modal/OptionModal.jsx
  src/contexts/CommentContext.jsx
  src/pages/LoginPage/LoginPage/LoginPage.jsx
Labels: 🔧 Fix

#407 [MERGE] 알파테스트 이슈 일부 반영
  src/components/Comment/Comment/Comment.jsx
  src/components/Comment/NestedComment/NestedComment.jsx
  src/components/Input/Input/SpecialInput.jsx
  src/components/InputBar/InputBar.jsx
  src/components/Modal/DeleteModal.jsx
  src/components/Modal/OptionModal.jsx
  src/components/PTR/PTR.jsx
  src/components/PTR/PTR.module.css
  src/constants/point.js
  src/contexts/CommentContext.jsx
  src/hooks/usePagination.jsx
  src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/LoginPage/FindIdPage/inputCheck.js
  src/pages/LoginPage/FindPwPage/FindPwPage.jsx
  src/pages/LoginPage/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage/LoginPage.module.css
  src/pages/MyPage/ActivityPage/CommentPage.jsx
  src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/MyPostPage.jsx
  src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/ScrapPage.jsx
Labels: 🌏 Deploy

#411 #410 [FIX] 시험후기 다운로드 후 마이페이지에 포인트 차감 반영이 안 되는 문제 해결
  src/apis/userInfo.js
  src/components/ReviewDownload/ReviewDownload.jsx
  src/hooks/useAuth.js
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
Labels: 🔧 Fix

#412 Fix/#402 sidebar nav error
  src/components/PTR/PTR.jsx
  src/components/PTR/PTR.module.css
  src/components/Sidebar/List/List.jsx
  src/components/Sidebar/Sidebar/Sidebar.jsx
  src/constants/menus.js
Labels: 🎨 UI

#416 #415 [FIX] PTR 드래그 잘 안 되는 오류 해결
  src/components/PTR/PTR.jsx
Labels: 🔧 Fix

#419 #418 [FIX] 에러 발생 시 빈 토스트가 노출되는 버그 해결
  src/pages/SnoroseVerifyPage/VerifyPage/VerifyPage.jsx
Labels: 🔧 Fix

#423 #422 [FIX] 사파리에서 아이콘 호환이 안 되는 버그 해결
  src/assets/icon.svg
  src/assets/images/completeVerification.svg
  src/assets/images/defaultProfile.svg
  src/pages/MyPage/EditInfoPage/EditInfoPage.jsx
  src/pages/MyPage/EditInfoPage/EditInfoPage.module.css
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage/MyPage.module.css
Labels: 🔧 Fix

#425 [MERGE] 알파테스트 버그 수정
  src/assets/icon.svg
  src/assets/images/completeVerification.svg
  src/assets/images/defaultProfile.svg
  src/components/ReviewDownload/ReviewDownload.jsx
  src/pages/MyPage/EditInfoPage/EditInfoPage.jsx
  src/pages/MyPage/EditInfoPage/EditInfoPage.module.css
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage/MyPage.module.css
  src/pages/SnoroseVerifyPage/VerifyPage/VerifyPage.jsx
Labels: 🌏 Deploy

#442 #441 [FIX] PTR 스크롤 오류 고치기 전까지 테스트 위해 이전 코드로 돌리기
  src/components/PTR/PTR.jsx
Labels: 🔧 Fix

#444 #424 [FEAT] favicon 추가
  public/favicon.ico
Labels: ✨ Feature

#445 [MERGE] 파비콘 추가
  public/favicon.ico
Labels: 🌏 Deploy

#448 #440 [FIX] PTR 오류 수정
  src/components/PTR/PTR.jsx
  src/components/PTR/PTR.module.css
  src/components/PostBar/PostBar.module.css
Labels: 🔧 Fix

#449 [MERGE] dev to main
  src/components/PTR/PTR.jsx
  src/components/PTR/PTR.module.css
  src/components/PostBar/PostBar.module.css
Labels: 🌏 Deploy

#453 [MERGE] iOS 버전 16에서 특정 아이콘이 비정상적으로 크게 보이는 문제 수정
  src/components/InputPassword/InputPassword.jsx
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/ViewPointListPage/ViewPointListPage.jsx
Labels: 🌏 Deploy

#455 #454 [FEAT] 숙명인 인증 페이지에 준회원 또는 관리자만 접근 가능
  src/route.js
Labels: ✨ Feature

#456 [MERGE] 숙명인 인증 페이지에 접근 권한 설정
  src/route.js
Labels: 🌏 Deploy

#458 #457 [FIX] 시험후기 상세에 누락된 온라인 여부 항목 추가
  src/components/Fieldset/TextField/TextField.module.css
  src/components/Input/InputItem/InputItem.jsx
  src/components/Input/InputItem/InputItem.module.css
  src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
Labels: 🔧 Fix

#459 [MERGE] 시험후기 상세에 누락된 온라인 수업 여부 필드 추가
  src/components/Fieldset/TextField/TextField.module.css
  src/components/Input/InputItem/InputItem.jsx
  src/components/Input/InputItem/InputItem.module.css
  src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
Labels: 🌏 Deploy

#461 #460 [MODIFY] 시험후기 상세에서 수강 연도를 두 자리수 숫자로 표기
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
Labels: 🪄 Modify

#463 [MERGE] 시험후기 상세에서 수강 연도를 두 자리로 표기
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
Labels: 🌏 Deploy

#465 #464 [FIX] 홈 화면의 출석체크 카드 줄바꿈 수정 및 카드 컴포넌트 배경 이미지 효과 수정
  src/assets/images/blueMegaphone.svg
  src/assets/images/flag.svg
  src/assets/images/megaphone.svg
  src/components/Card/Card.jsx
  src/components/Card/Card.module.css
  src/pages/MainPage/MainPage.jsx
Labels: 🔧 Fix

#466 [MERGE] 홈 화면 카드 컴포넌트의 부자연스러운 줄바꿈 수정
  src/assets/images/blueMegaphone.svg
  src/assets/images/flag.svg
  src/assets/images/megaphone.svg
  src/components/Card/Card.jsx
  src/components/Card/Card.module.css
  src/pages/MainPage/MainPage.jsx
Labels: 🌏 Deploy

#468 #467 [STYLE] 하단 Navbar 높이 축소 및 아이콘 크기 확대
  src/assets/icon.svg
  src/components/Footer/Footer.module.css
  src/components/Navbar/Navbar.module.css
  src/constants/menus.js
Labels: 🎨 UI

#469 [MERGE] Navbar 높이 및 아이콘 크기 변경
  src/assets/icon.svg
  src/components/Footer/Footer.module.css
  src/components/Navbar/Navbar.module.css
  src/constants/menus.js
Labels: 🌏 Deploy

#471 #450 [FIX] 리자 아닌 유저가 게시글 수정할 때 공지글 선택 옵션 보이는 오류 수정 & 방어 모달
  src/components/AppBar/CloseAppBar/CloseAppBar.jsx
  src/components/Modal/Modal.module.css
  src/constants/modalOptions.js
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
Labels: ✨ Feature, 🔧 Fix

#473 #470 [FIX] 시험후기 검색에서 Navbar의 강조가 풀리는 버그 수정
  src/components/Navbar/Navbar.jsx
Labels: 🔧 Fix

#474 [MERGE] Navbar 강조 버그 해결
  src/components/AppBar/CloseAppBar/CloseAppBar.jsx
  src/components/Modal/Modal.module.css
  src/components/Navbar/Navbar.jsx
  src/constants/modalOptions.js
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
Labels: 🌏 Deploy

#475 #472 [FIX] 게시글 & 댓글의 input 관련 오류 해결
  src/components/Comment/Comment/Comment.module.css
  src/components/InputBar/InputBar.jsx
  src/contexts/CommentContext.jsx
Labels: 🔧 Fix

#479 #391 [FIX] 기존 신고하기 API 및 모달 일부 수정
  src/apis/comment.js
  src/apis/post.js
  src/pages/PostPage/PostPage/PostPage.jsx
Labels: 🐞 Bug

#481 #480 [MODIFY] 강등 회원(blacklist) 등급 추가
  package-lock.json
  src/ProtectedRoute.jsx
  src/constants/role.js
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/route.js
Labels: 🪄 Modify

#482 #476 [FIX] AppBar 상단 고정 (position: fixed)
  src/components/AppBar/AppBar/AppBar.jsx
  src/components/AppBar/AppBar/AppBar.module.css
  src/components/AppBar/BackAppBar/BackAppBar.jsx
  src/components/AppBar/BackAppBar/BackAppBar.module.css
  src/components/AppBar/CloseAppBar/CloseAppBar.jsx
  src/components/AppBar/CloseAppBar/CloseAppBar.module.css
  src/components/Comment/Comment/Comment.jsx
  src/pages/AttendancePage/AttendancePage.jsx
  src/pages/AttendancePage/AttendancePage.module.css
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
  src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx
  src/pages/ExamReviewEditPage/ExamReviewEditPage.module.css
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css
  src/pages/ExamReviewWritePage/ExamReviewWritePage.module.css
  src/pages/MyPage/ActivityPage/ActivityPage.module.css
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
  src/pages/MyPage/DeleteAccountPage/DeleteAccountPage.jsx
  src/pages/MyPage/EditInfoPage/EditInfoPage.jsx
  src/pages/MyPage/PolicyPage/PolicyPage.module.css
  src/pages/MyPage/ViewPointListPage/ViewPointListPage.module.css
  src/pages/NoticeListPage/NoticeListPage.jsx
  src/pages/NoticeListPage/NoticeListPage.module.css
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.module.css
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostPage/PostPage.module.css
  src/pages/PostPage/PostSearchPage/PostSearchPage.module.css
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.module.css
  src/pages/SnoroseVerifyPage/SnoroseVerifyPage.jsx
Labels: 🔧 Fix

#485 #484 [FIX] FetchLoading & InputBar와Modal 겹치는 오류 해결 & 한 줄 공지 폰트사이즈 키우기
  src/components/Modal/Modal.module.css
  src/components/PostBar/PostBar.module.css
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
Labels: 🔧 Fix

#413 #385 [MODIFY] 좋아요, 스크랩 캐시 업데이트
  src/apis/comment.js
  src/apis/like.js
  src/apis/scrap.js
  src/components/Calendar/Calendar.jsx
  src/components/Carousel/Carousel/Carousel.jsx
  src/components/Comment/Comment/Comment.jsx
  src/components/Comment/CommentList/CommentList.jsx
  src/components/Comment/NestedComment/NestedComment.jsx
  src/components/InputBar/InputBar.jsx
  src/components/Modal/ConfirmModal/ConfirmModal.jsx
  src/components/ReviewDownload/ReviewDownload.jsx
  src/constants/index.js
  src/constants/reactQuery.js
  src/constants/type.js
  src/hooks/useAuth.js
  src/hooks/useComment.jsx
  src/hooks/useLike.jsx
  src/hooks/usePagination.jsx
  src/hooks/useScrap.jsx
  src/hooks/useSearch.jsx
  src/pages/AttendancePage/AttendancePage.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/MyPage/ActivityPage/CommentPage.jsx
  src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/MyPostPage.jsx
  src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/ScrapPage.jsx
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
  src/pages/MyPage/EditInfoPage/EditInfoPage.jsx
  src/pages/MyPage/ViewPointListPage/ViewPointListPage.jsx
  src/pages/NoticeListPage/NoticeListPage.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/utils/comment.js
  src/utils/debounce.js
  src/utils/index.js
Labels: 🔧 Fix, 🪄 Modify

#490 #326 [FEAT] 시험후기 신고 API 연동
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
Labels: 📬 API

#492 #491 [FIX] 사용자 신고 코드 임시 주석 처리 (베타테스트를 위한)
  src/constants/modalOptions.js
Labels: 🔧 Fix

#494 #493 [FIX] 시험후기 수정 화면에서 체크박스에 대한 비제어 컴포넌트 버그 수정
  src/components/Fieldset/Fieldset/Fieldset.jsx
  src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
Labels: 🔧 Fix

#497 [MERGE] 프로덕션 브랜치에 머지
  src/components/Fieldset/Fieldset/Fieldset.jsx
  src/constants/modalOptions.js
  src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
Labels: 🌏 Deploy

#504 #486 [FIX] 다른 게시판 선택 후 글쓰기 시, 게시글 작성/수정 후 backbar 클릭 시, nav 에러 해결
  src/pages/MyPage/ActivityPage/CommentPage.jsx
  src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/MyPostPage.jsx
  src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/ScrapPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
Labels: 🔧 Fix

#506 #505 [FIX] 만년설방, 시험후기 페이지에서 댓글 삭제 시, 모달에 포인트 관련 내용 안 뜨도록 수정
  src/components/Comment/Comment/Comment.jsx
  src/constants/modalOptions.js
  src/pages/PostPage/PostPage/PostPage.jsx
Labels: 🔧 Fix

#509 #507 [FIX] DeleteModal 닫기 함수명 closeFn으로 수정하여 다른 모달들과 이름 통일
  src/components/Comment/Comment/Comment.jsx
  src/components/Modal/DeleteModal.jsx
  src/components/ReviewDownload/ReviewDownload.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
Labels: 🔧 Fix
