Repository snorose/snorose-front-react, pull requests merged in 2024-08, with the labels that each got.

#75 #67 [FEAT] 게시글 상세 페이지 & 아이콘 일괄 수정
  src/assets/icon.svg
  src/components/AppBar/BackAppBar/BackAppBar.jsx
  src/components/AppBar/BackAppBar/BackAppBar.module.css
  src/components/AppBar/CloseAppBar/CloseAppBar.jsx
  src/components/BoardHeader/BoardHeader.jsx
  src/components/BoardHeader/BoardHeader.module.css
  src/components/Comment/Comment/Comment.jsx
  src/components/Comment/Comment/Comment.module.css
  src/components/Comment/NestedComment/NestedComment.jsx
  src/components/Footer/Footer.jsx
  src/components/Header/Header.module.css
  src/components/InputBar/InputBar.jsx
  src/components/InputBar/InputBar.module.css
  src/components/ListHeader/ListHeader.jsx
  src/components/MainPageListItem/MainPageListItem.jsx
  src/components/MenuIcon/MenuIcon.jsx
  src/components/PostBar/PostBar.jsx
  src/components/PostBar/PostBar.module.css
  src/dummy/data/comment.js
  src/dummy/data/postContent.js
  src/dummy/data/postList.js
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
  src/pages/BoardPage/BoardPage/BoardPage.jsx
  src/pages/BoardPage/BoardPage/BoardPage.module.css
  src/pages/LoginPage/LoginPage/LoginPage.jsx
  src/pages/MyPage/DeleteAccountPage/DeleteAccountPage.jsx
  src/pages/MyPage/EditInfoPage/EditInfoPage.jsx
  src/pages/MyPage/ViewPointListPage/ViewPointListPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostPage/PostPage.module.css
Labels: ✨ Feature, 🛠️ Refactor

#78 #76 [FEAT] 게시글 작성 페이지 UI 구현 & 드롭다운 컴포넌트 추가
  package.json
  src/assets/icon.svg
  src/components/AppBar/CloseAppBar/CloseAppBar.jsx
  src/components/DropDownMenu/DropDownMenu.jsx
  src/components/DropDownMenu/DropDownMenu.module.css
  src/components/DropDownMenu/index.js
  src/constants/toast.js
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.module.css
  src/utils/formattedNowTime.js
Labels: ✨ Feature

#79 #64 [FEAT] 시험 후기 작성 기능
  src/apis/examReview.js
  src/apis/index.js
  src/assets/icon.svg
  src/axios/index.js
  src/components/Fieldset/CategoryButton/CategoryButton.jsx
  src/components/Fieldset/CategoryButton/CategoryButton.module.css
  src/components/Fieldset/Dropdown/Dropdown.jsx
  src/components/Fieldset/Dropdown/Dropdown.module.css
  src/components/Fieldset/Fieldset/Fieldset.jsx
  src/components/Fieldset/Fieldset/Fieldset.module.css
  src/components/Fieldset/Textarea/Textarea.jsx
  src/components/Fieldset/Textarea/Textarea.module.css
  src/components/Fieldset/index.js
  src/components/Input/Input/Input.jsx
  src/components/Input/Input/Input.module.css
  src/components/Input/InputItem/InputItem.jsx
  src/components/Input/InputItem/InputItem.module.css
  src/components/Input/InputList/InputList.jsx
  src/components/Input/InputList/InputList.module.css
  src/components/Input/index.js
  src/components/Navbar/Navbar.jsx
  src/constants/index.js
  src/constants/menuWithoutNav.js
  src/constants/menus.js
  src/constants/test.js
  src/index.js
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.module.css
Labels: 📬 API, 🎨 UI, ✨ Feature

#68 #49 [FEAT] 마이페이지 구현
  src/assets/icon-profile.svg
  src/assets/icon.svg
  src/assets/images/symbol_White.png
  src/assets/logo-white.svg
  src/assets/mypage-background-gradation.svg
  src/index.js
  src/pages/MyPage/ActivityPage/ActivityPage.module.css
  src/pages/MyPage/ActivityPage/CommentPage.jsx
  src/pages/MyPage/ActivityPage/DownloadTestReviewPage.jsx
  src/pages/MyPage/ActivityPage/MyPostPage.jsx
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
  src/pages/MyPage/MyPage/AccountTab.jsx
  src/pages/MyPage/MyPage/ActivityTab.jsx
  src/pages/MyPage/MyPage/GuideTab.jsx
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage/MyPage.module.css
  src/pages/MyPage/PolicyPage/PolicyPage.module.css
  src/pages/MyPage/PolicyPage/PrivacyPolicyPage.jsx
  src/pages/MyPage/PolicyPage/ServicePolicyPage.jsx
  src/pages/MyPage/ViewPointListPage/ViewPointListPage.jsx
  src/pages/MyPage/index.js
Labels: 🎨 UI, ✨ Feature

#86 #85 [FEAT] 개인 정보 처리 방침, 서비스 이용 약관 페이지 구현
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage/PolicyTab.jsx
  src/pages/MyPage/PolicyPage/PolicyPage.module.css
  src/pages/MyPage/PolicyPage/PrivacyPolicyPage.jsx
  src/pages/MyPage/PolicyPage/ServicePolicyPage.jsx
Labels: ✨ Feature

#90 #87 [FEAT] 포인트 내역 보기 페이지 UI 구현
  src/pages/MyPage/ViewPointListPage/ViewPointListPage.jsx
  src/pages/MyPage/ViewPointListPage/ViewPointListPage.module.css
Labels: 🎨 UI, ✨ Feature

#37 #31 [FIX] Login페이지- JWT 토큰들만 localStorage에 저장하기
  src/assets/icon.svg
  src/assets/images/snoroseLogo.svg
  src/components/Input/Input/Input.jsx
  src/components/Input/Input/Input.module.css
  src/pages/LoginPage/FindIdPage/FindIdPage.jsx
  src/pages/LoginPage/FindIdPage/FindIdPage.module.css
  src/pages/LoginPage/FindPwPage/FindPwPage.jsx
  src/pages/LoginPage/FindPwPage/FindPwPage.module.css
  src/pages/LoginPage/FoundPwPage/FoundPwPage.jsx
  src/pages/LoginPage/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage/LoginPage.module.css
  src/pages/LoginPage/authorize.js
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
Labels: 🔧 Fix

#81 #80 [FIX] localhost:3000에 있을 때 Navbar의 홈 아이콘이 활성화되지 않는 문제 해결
  src/components/Navbar/Navbar.jsx
Labels: 🔧 Fix

#100 #97 [FEAT] 시험 후기 리스트 API 연결
  package.json
  src/apis/examReview.js
  src/components/AppBar/AppBar/AppBar.jsx
  src/components/AppBar/AppBar/AppBar.module.css
  src/components/AppBar/index.js
  src/components/Loading/Loading.jsx
  src/components/Loading/Loading.module.css
  src/components/Loading/index.js
  src/components/Search/Search.jsx
  src/components/Target/Target.jsx
  src/components/Target/index.js
  src/dummy/data/index.js
  src/dummy/data/review.js
  src/hooks/useIntersect.jsx
  src/index.js
  src/pages/ExamReviewPage/ExamReviewPage.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css
  src/pages/ExamReviewPage/ReviewDetailPage/ReviewDetailPage.jsx
  src/pages/ExamReviewPage/index.js
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
  yarn.lock
Labels: 📬 API

#98 #95 [FEAT] 알림페이지 UI 구현
  src/assets/arrow text_grey.svg
  src/assets/icon-arrow-back.svg
  src/assets/icon-eye.svg
  src/assets/icon.svg
  src/pages/AlertPage/AlertPage.jsx
  src/pages/AlertPage/AlertPage.module.css
  src/pages/MyPage/MyPage/MyPage.jsx
Labels: 🎨 UI

#102 #94 [FEAT] 공지글 리스트 페이지 UI 구현
  src/components/Notice/Notice.jsx
  src/components/Notice/Notice.module.css
  src/components/Notice/index.js
  src/components/NoticeBar/NoticeBar.jsx
  src/components/NoticeBar/NoticeBar.module.css
  src/components/NoticeBar/index.js
  src/dummy/data/noticeList.js
  src/index.js
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/NoticeListPage/NoticeListPage.jsx
  src/pages/NoticeListPage/NoticeListPage.module.css
  src/pages/NoticeListPage/index.js
  src/pages/NoticePage/NoticePage.jsx
  src/pages/NoticePage/index.js
  src/pages/PostPage/PostSearchPage/PostSearchPage.jsx
  src/pages/PostPage/PostSearchPage/PostSearchPage.module.css
  src/pages/PostPage/PostSearchPage/index.js
  src/pages/SearchPage/SearchPage.jsx
  src/pages/SearchPage/index.js
Labels: 🎨 UI, ✨ Feature

#103 #99 [FEAT] 모달 컴포넌트 생성
  src/assets/icon.svg
  src/components/Modal/DeleteModal.jsx
  src/components/Modal/Modal.module.css
  src/components/Modal/OptionModal.jsx
  src/components/Modal/Options.jsx
  src/components/Modal/TextAreaModal.jsx
  src/components/Modal/index.js
  src/components/PostBar/PostBar.jsx
  src/components/PostBar/PostBar.module.css
  src/constants/modalOptions.js
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
Labels: 🎨 UI, ✨ Feature

#106 #105 [FIX] 시험후기 리스트 API 에러 핸들링
  src/ProtectedRoute.jsx
  src/apis/examReview.js
  src/contexts/ToastContext.jsx
  src/index.js
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
Labels: 🔧 Fix

#111 #110 [REFACTOR] 라우트에 따른 조건부 렌더링 로직 개선
  src/App.jsx
  src/constants/menuWithoutNav.js
  src/index.js
  src/route.js
  src/utils/findRoute.js
Labels: 🛠️ Refactor

#107 #101 [FEAT] 로그인 상태에 따라 Header에 로그인/로그아웃 버튼 핸들링
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/index.css
Labels: ✨ Feature

#112 #108 [STYLE] PC 디스플레이 너비를 600px로 조정
  src/App.module.css
  src/components/Modal/Modal.module.css
  src/components/Navbar/Navbar.module.css
  src/components/Sidebar/Sidebar/Sidebar.module.css
  src/index.css
Labels: 🎨 UI

#113 #109 [FEAT] 시험후기 상세 페이지 UI
  src/ProtectedRoute.jsx
  src/assets/icon.svg
  src/components/Comment/Comment/Comment.jsx
  src/components/Comment/Comment/Comment.module.css
  src/components/Comment/NestedComment/NestedComment.jsx
  src/components/InputBar/InputBar.jsx
  src/components/InputBar/InputBar.module.css
  src/components/ReviewContentItem/ReviewContentItem.jsx
  src/components/ReviewContentItem/ReviewContentItem.module.css
  src/components/ReviewContentItem/index.js
  src/components/ReviewDownload/ReviewDownload.jsx
  src/components/ReviewDownload/ReviewDownload.module.css
  src/dummy/data/comment.js
  src/dummy/data/index.js
  src/dummy/data/review.js
  src/index.css
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/ExamReviewPage/ReviewDetailPage/ReviewDetailPage.jsx
  src/pages/ExamReviewPage/index.js
  src/pages/PostPage/PostPage/PostPage.jsx
  src/route.js
  src/utils/convertDS.js
  src/utils/formatDate.js
Labels: 🎨 UI

#115 #114 [STYLE] InputBar의 max-width 수정
  src/components/InputBar/InputBar.module.css
Labels: 🎨 UI

#116 #104 [API] 게시판 리스트 api 연결
  src/apis/postList.js
  src/components/BoardBar/BoardBar.jsx
  src/components/PTR/PTR.jsx
  src/components/PostBar/PostBar.jsx
  src/components/PostBar/PostBar.module.css
  src/constants/boardMenus.js
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
  src/pages/PostPage/PostPage/PostPage.jsx
  src/route.js
Labels: 📬 API

#119 #69 [MODIFY] 회원탈퇴 페이지 UI 수정 및 API 연동
  src/apis/userInfo.js
  src/pages/MyPage/DeleteAccountPage/DeleteAccountPage.jsx
  src/pages/MyPage/DeleteAccountPage/DeleteAccountPage.module.css
Labels: 📬 API, 🎨 UI, ✨ Feature

#120 #69 [STYLE] 내 정보 수정 페이지 UI 수정
  src/assets/icon.svg
  src/constants/index.js
  src/constants/majors.js
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.module.css
  src/pages/MyPage/EditInfoPage/EditInfoPage.jsx
  src/pages/MyPage/EditInfoPage/EditInfoPage.module.css
Labels: 🎨 UI, ✨ Feature

#125 #117 [FEAT] 게시글 상세 조회 API 연결
  src/apis/comment.js
  src/apis/postContent.js
  src/components/Comment/Comment/Comment.jsx
  src/components/Comment/Comment/Comment.module.css
  src/components/Comment/NestedComment/NestedComment.jsx
  src/components/InputBar/InputBar.jsx
  src/components/Loading/FetchLoading.jsx
  src/components/Loading/FetchLoading.module.css
  src/components/Loading/index.js
  src/components/Modal/DeleteModal.jsx
  src/components/Modal/Modal.module.css
  src/components/Modal/OptionModal.jsx
  src/components/Modal/Options.jsx
  src/constants/modalOptions.js
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostPage/PostPage.module.css
Labels: 📬 API

#123 #122 [FEAT] 시험후기 다운로드 API 연결
  src/apis/examReview.js
  src/apis/index.js
  src/components/Modal/DeleteModal.jsx
  src/components/ReviewDownload/ReviewDownload.jsx
  src/constants/modalOptions.js
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
Labels: 📬 API

#127 #126 [FEAT] 로그아웃 기능 구현
  craco.config.js
  jsconfig.json
  package.json
  src/components/Header/Header.jsx
  src/hooks/index.js
  src/hooks/useAuth.js
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/MyPage/MyPage/PolicyTab.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
  yarn.lock
Labels: ✨ Feature, 🛠️ Refactor

#129 #126 [FEAT] 회원탈퇴 API 코드 개선 및 비밀번호 확인 입력창 추가
  src/apis/index.js
  src/apis/userInfo.js
  src/hooks/useAuth.js
  src/pages/MyPage/DeleteAccountPage/DeleteAccountPage.jsx
Labels: 📬 API

#134 #133 [MODIFY] craco 공식 라이브러리로 수정
  package.json
  yarn.lock
Labels: 🔧 Fix

#135 #131 [MODIFY] bottom navigation이 필요없는 페이지는 제거 및 padding-bottom 크기 조정
  src/pages/MyPage/ActivityPage/ActivityPage.module.css
  src/pages/MyPage/DeleteAccountPage/DeleteAccountPage.module.css
  src/pages/MyPage/PolicyPage/PolicyPage.module.css
  src/pages/MyPage/ViewPointListPage/ViewPointListPage.jsx
  src/pages/MyPage/ViewPointListPage/ViewPointListPage.module.css
  src/route.js
Labels: 🎨 UI

#137 #136 [REFACTOR] 비밀번호 input 창 컴포넌트화 및 적용
  src/assets/icon.svg
  src/components/InputPassword/InputPassword.jsx
  src/components/InputPassword/InputPassword.module.css
  src/components/InputPassword/index.js
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.module.css
  src/pages/MyPage/DeleteAccountPage/DeleteAccountPage.jsx
  src/pages/MyPage/DeleteAccountPage/DeleteAccountPage.module.css
Labels: 🛠️ Refactor

#130 #124 [FEAT] 시험후기 페이지 댓글 조회, 생성, 삭제, 조회 API 연결
  src/apis/comment.js
  src/components/Comment/Comment/Comment.jsx
  src/components/Comment/Comment/Comment.module.css
  src/components/Comment/CommentList/CommentList.jsx
  src/components/Comment/CommentList/CommentList.module.css
  src/components/Comment/NestedComment/NestedComment.jsx
  src/components/Comment/index.js
  src/components/InputBar/InputBar.jsx
  src/components/Modal/Modal.module.css
  src/components/Modal/OptionModal.jsx
  src/contexts/CommentContext.jsx
  src/hooks/useComment.jsx
  src/index.js
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostPage/PostPage.module.css
  src/utils/filterComment.js
Labels: 📬 API

#139 #138 [FEAT] 인증 신청 페이지 UI
  src/ProtectedRoute.jsx
  src/assets/icon.svg
  src/assets/images/completeVerification.svg
  src/constants/index.js
  src/constants/verify.js
  src/pages/SnoroseVerifyPage/Button/Button.jsx
  src/pages/SnoroseVerifyPage/Button/Button.module.css
  src/pages/SnoroseVerifyPage/CompletePage/CompletePage.jsx
  src/pages/SnoroseVerifyPage/CompletePage/CompletePage.module.css
  src/pages/SnoroseVerifyPage/Input/Input.jsx
  src/pages/SnoroseVerifyPage/Input/Input.module.css
  src/pages/SnoroseVerifyPage/SnoroseVerifyPage.jsx
  src/pages/SnoroseVerifyPage/SnoroseVerifyPage.module.css
  src/pages/SnoroseVerifyPage/TermsPage/TermsPage.jsx
  src/pages/SnoroseVerifyPage/TermsPage/TermsPage.module.css
  src/pages/SnoroseVerifyPage/VerifyPage/VerifyPage.jsx
  src/pages/SnoroseVerifyPage/VerifyPage/VerifyPage.module.css
  src/pages/SnoroseVerifyPage/index.js
  src/route.js
Labels: 🎨 UI

#141 #140 [FEAT] 시험후기 포인트 API 연결
  src/apis/index.js
  src/apis/point.js
  src/components/ReviewDownload/ReviewDownload.jsx
  src/constants/index.js
  src/constants/point.js
  src/constants/toast.js
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
Labels: 📬 API

#145 #128 [FEAT] 마이페이지 API 연동
  package.json
  src/App.jsx
  src/apis/userInfo.js
  src/assets/icon.svg
  src/components/AppBar/ActionButton/ActionButton.jsx
  src/components/InputPassword/InputPassword.jsx
  src/constants/index.js
  src/constants/role.js
  src/hooks/useAuth.js
  src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
  src/pages/MyPage/DeleteAccountPage/DeleteAccountPage.jsx
  src/pages/MyPage/EditInfoPage/EditInfoPage.jsx
  src/pages/MyPage/EditInfoPage/EditInfoPage.module.css
  src/pages/MyPage/MyPage/AccountTab.jsx
  src/pages/MyPage/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage/MyPage.module.css
  yarn.lock
Labels: 📬 API, ✨ Feature

#149 #148 [STYLE] 시험후기 상세 페이지 댓글, 북마크 아이콘 추가
  src/assets/icon.svg
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css
Labels: 🎨 UI

#151 #150 [STYLE] 시험후기 작성 페이지 온라인 선택 필드 추가 & 글작성 플로팅 버튼 추가
  src/components/WriteButton/WriteButton.jsx
  src/components/WriteButton/WriteButton.module.css
  src/components/WriteButton/index.js
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
Labels: 🎨 UI

#157 #156 [FEAT] 공지글 조회 API 연결
  src/apis/notice.js
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/NoticeListPage/NoticeListPage.jsx
Labels: 📬 API

#143 #132 [FEAT] 게시글 작성 / 수정 / 삭제 API 연결
  src/apis/comment.js
  src/apis/index.js
  src/apis/post.js
  src/apis/postContent.js
  src/apis/postList.js
  src/components/AppBar/CloseAppBar/CloseAppBar.jsx
  src/components/Comment/Comment/Comment.jsx
  src/components/Comment/Comment/Comment.module.css
  src/components/Comment/NestedComment/NestedComment.jsx
  src/components/Modal/DeleteModal.jsx
  src/components/PostBar/PostBar.jsx
  src/components/ReviewDownload/ReviewDownload.jsx
  src/constants/toast.js
  src/hooks/useComment.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/NoticeListPage/NoticeListPage.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.module.css
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostPage/PostPage.module.css
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
  src/pages/PostPage/index.js
  src/route.js
  yarn.lock
Labels: 📬 API, ✨ Feature

#159 #158 게시글 검색 API 연결
  src/apis/search.js
  src/components/Loading/FetchLoading.module.css
  src/components/PostBar/PostBar.jsx
  src/components/Search/Search.jsx
  src/components/Search/Search.module.css
  src/pages/BoardPage/BoardPage/BoardPage.jsx
  src/pages/PostPage/PostSearchPage/PostSearchPage.jsx
  src/route.js
  yarn.lock
Labels: 📬 API, ✨ Feature

#168 #166 [MODIFY] isWriterWithdrawn, isDeleted, isVisible에 따라 대체 텍스트 표시 i…
  src/components/Comment/Comment/Comment.jsx
  src/components/Comment/Comment/Comment.module.css
  src/components/Comment/CommentList/CommentList.jsx
  src/components/Comment/NestedComment/NestedComment.jsx
  yarn.lock
Labels: 🪄 Modify

#170 #169 [FEAT] 시험후기 스크랩 관련 API 연결
  src/apis/index.js
  src/apis/scrap.js
  src/constants/index.js
  src/constants/menuWithoutNav.js
  src/hooks/index.js
  src/hooks/useScrap.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
Labels: 📬 API, ✨ Feature

#165 #155 [FEAT] 출석체크 페이지 UI
  package.json
  src/assets/icon.svg
  src/components/AppBar/BackAppBar/BackAppBar.jsx
  src/components/AppBar/BackAppBar/BackAppBar.module.css
  src/components/Calendar/Calendar.jsx
  src/components/Calendar/Calendar.style.jsx
  src/components/Calendar/Tile/Tile.jsx
  src/components/Calendar/Tile/Tile.module.css
  src/components/Calendar/index.js
  src/pages/AttendancePage/AttendancePage.jsx
  src/pages/AttendancePage/AttendancePage.module.css
  src/pages/AttendancePage/index.js
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/MainPage/MainPage.jsx
  src/route.js
  src/utils/date.js
  yarn.lock
Labels: 🎨 UI

#167 #164 [MODIFY] 탈퇴 여부를 묻는 모달창 추가 및 `sponsor`로 오탈자 수정
  public/index.html
  src/assets/icon.svg
  src/assets/images/sponsor.svg
  src/components/Modal/ConfirmModal/ConfirmModal.jsx
  src/components/Modal/ConfirmModal/ConfirmModal.module.css
  src/components/Modal/ConfirmModal/index.js
  src/components/Modal/index.js
  src/components/Portal/Portal.jsx
  src/components/Portal/index.js
  src/components/Sponser/Sponser.jsx
  src/components/Sponser/index.js
  src/components/Sponsor/Sponsor.jsx
  src/components/Sponsor/index.js
  src/components/index.js
  src/hooks/index.js
  src/hooks/useAuth.js
  src/hooks/useModal.js
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
  src/pages/BoardPage/BoardListPageHasCategory/BoardListPageHasCategory.jsx
  src/pages/BoardPage/BoardListPageHasCategory/BoardListPageHasCategory.module.css
  src/pages/BoardPage/BoardPage/BoardPage.jsx
  src/pages/BoardPage/BoardPage/BoardPage.module.css
  src/pages/MyPage/ActivityPage/CommentPage.jsx
  src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/MyPostPage.jsx
  src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
  src/pages/MyPage/ActivityPage/ScrapPage.jsx
  src/pages/MyPage/DeleteAccountPage/DeleteAccountPage.jsx
Labels: 🎨 UI

#176 #173 [FEAT] 시험후기 상세 페이지에 수정/삭제 모달 연결
  src/constants/modalOptions.js
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css
Labels: ✨ Feature

#179 #178 [STYLE] 숫자값에 toLocaleString() 추가
  src/components/Comment/Comment/Comment.jsx
  src/components/Comment/CommentList/CommentList.jsx
  src/components/Comment/NestedComment/NestedComment.jsx
  src/components/NoticeBar/NoticeBar.jsx
  src/components/PostBar/PostBar.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
Labels: 🎨 UI

#175 #174 [STYLE] Toast 위치를 정중앙으로 수정
  src/components/Toast/Toast.module.css
  src/index.css
Labels: 🎨 UI

#163 #162 [FEAT] 포인트 내역 보기 페이지 API 연동
  package.json
  src/apis/point.js
  src/constants/point.js
  src/pages/MyPage/ViewPointListPage/ViewPointListPage.jsx
  yarn.lock
Labels: 📬 API

#180 #160 [FEAT] 스크랩 & 좋아요 API 연결, 자잘한 수정
  src/apis/like.js
  src/assets/icon.svg
  src/components/Comment/Comment/Comment.jsx
  src/components/Comment/CommentList/CommentList.jsx
  src/components/Comment/CommentList/CommentList.module.css
  src/components/Comment/NestedComment/NestedComment.jsx
  src/components/PostBar/PostBar.jsx
  src/components/PostBar/PostBar.module.css
  src/components/WriteButton/WriteButton.jsx
  src/constants/modalOptions.js
  src/constants/toast.js
  src/hooks/index.js
  src/hooks/useComment.jsx
  src/hooks/useLike.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostPage/PostPage.module.css
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
  yarn.lock
Labels: 📬 API, 🎨 UI, ✨ Feature

#182 #181 [REFACTOR] 좋아요 로직 수정
  src/apis/index.js
  src/components/Comment/Comment/Comment.jsx
  src/components/Comment/NestedComment/NestedComment.jsx
  src/components/PostBar/PostBar.jsx
  src/components/index.js
  src/constants/boardMenus.js
  src/constants/toast.js
  src/hooks/index.js
  src/hooks/useComment.jsx
  src/hooks/useLike.jsx
  src/hooks/useScrap.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.module.css
Labels: 🛠️ Refactor, 🔧 Fix

#184 #183 [STYLE] NoticeBar UI 수정 & FetchLoading 적용
  src/components/Loading/FetchLoading.jsx
  src/components/Loading/FetchLoading.module.css
  src/components/NoticeBar/NoticeBar.jsx
  src/components/NoticeBar/NoticeBar.module.css
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/NoticeListPage/NoticeListPage.jsx
Labels: 🎨 UI

#187 #186 [FEAT] 스크랩 에러 핸들링 및 시험후기 페이지 스크랩 아이콘 수정
  src/components/Comment/Comment/Comment.module.css
  src/constants/toast.js
  src/hooks/useScrap.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css
Labels: 🎨 UI, ✨ Feature

#189 #188 [FIX] useScrap import 중복 제거
  src/hooks/useScrap.jsx
Labels: 🔧 Fix

#191 #190 [MODIFY] 사이드바에서 변경된 경로 수정 및 2차 배포로 밀린 기능 숨김
  src/components/MenuIcon/MenuIcon.jsx
  src/components/Sidebar/Sidebar/Sidebar.jsx
  src/constants/menus.js
Labels: 🪄 Modify

#193 #192 [FEAT] 홈 공지 API 연결
  src/apis/index.js
  src/apis/notice.js
  src/components/Header/Header.jsx
  src/pages/MainPage/MainPage.jsx
Labels: 📬 API

#172 #171 [FIX] 검색 기능 하나로 통일, 실시간 검색으로 기능 변경
  src/apis/search.js
  src/components/Search/Search.jsx
  src/hooks/index.js
  src/hooks/useInfiniteScroll.jsx
  src/hooks/useSearch.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/BoardPage/BoardPage/BoardPage.jsx
  src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css
  src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
  src/pages/ExamReviewPage/index.js
  src/pages/PostPage/PostSearchPage/PostSearchPage.jsx
  src/utils/debounce.js
  src/utils/index.js
Labels: 🔧 Fix, 🪄 Modify

#199 #198 [MODIFY] 삭제된 댓글의 대댓글, 좋아요 아이콘 숨김
  src/components/Comment/Comment/Comment.jsx
  src/components/Comment/Comment/Comment.module.css
  src/components/Comment/NestedComment/NestedComment.jsx
  src/components/PostBar/PostBar.jsx
  src/pages/BoardPage/BoardListPage/BoardListPage.jsx
  src/pages/PostPage/PostEditPage/PostEditPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
  src/utils/formattedNowTime.js
  src/utils/timeAgo.js
Labels: 🪄 Modify

#201 #200 [STYLE] 시험후기 상세 페이지의 댓글 아이콘 색상 회색으로 변경
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
Labels: 🎨 UI

#203 #202 [MODIFY] 시험후기 필터
  src/components/DropDownBlue/DropDownBlue.jsx
  src/components/DropDownBlue/DropDownBlue.module.css
  src/constants/dropDown.js
  src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
Labels: 🪄 Modify

#213 #210 [MODIFY] 포인트 내역 보기 내 '시험후기 삭제' enum 추가
  src/constants/point.js
Labels: 🪄 Modify

#205 #204 [FEAT] 출석체크 관련 API 연결
  src/apis/point.js
  src/components/Calendar/Calendar.jsx
  src/components/Calendar/Tile/Tile.jsx
  src/components/Calendar/Tile/Tile.module.css
  src/components/Toast/Toast.module.css
  src/constants/toast.js
  src/pages/AttendancePage/AttendancePage.jsx
Labels: 📬 API

#206 #185 [FEAT] 게시글 작성/삭제 포인트 API 연결
  src/apis/post.js
  src/constants/toast.js
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
Labels: 📬 API

#214 #207 [STYLE] 게시글에 신고 옵션 UI 수정
  src/assets/icon.svg
  src/components/Modal/Modal.module.css
  src/constants/modalOptions.js
  src/pages/PostPage/PostPage/PostPage.jsx
Labels: 🎨 UI, 🛠️ Refactor

#218 #216 [FEAT] 댓글 포인트 API
  src/components/InputBar/InputBar.jsx
  src/constants/toast.js
  src/hooks/useComment.jsx
Labels: 📬 API

#223 #212 [MODIFY] 이름, 생년월일 변경 불가를 보여주도록 UI 수정
  src/constants/role.js
  src/pages/MyPage/EditInfoPage/EditInfoPage.jsx
  src/pages/MyPage/EditInfoPage/EditInfoPage.module.css
Labels: 🎨 UI, ✨ Feature

#226 #225 [FEAT] yarn.lock 파일 재설치 (4.1.1 ver)
  yarn.lock
Labels: ✨ Feature

#230 #229 [FIX] yarn.lock 최신화
  yarn.lock
Labels: 🔧 Fix

#232 #231 [FIX] package.json packageManager 삭제 (빌드 오류)
  package.json
Labels: 🔧 Fix

#236 [MERGE] 서버 프로토콜 https로 변경
  src/axios/index.js
Labels: 🌏 Deploy

#238 #237 [FEAT] 서버 도메인 변경 및 환경변수로 분리
  .gitignore
  src/axios/index.js
Labels: ✨ Feature

#239 [MERGE] 서버 도메인 변경 및 환경변수로 분리
  .gitignore
  src/axios/index.js
Labels: 🌏 Deploy

#219 #177 [FIX] 시험후기 수정 404 오류 수정
  src/constants/index.js
  src/constants/route.js
  src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx
Labels: 🔧 Fix

#241 #240 [FIX] 로그인 요청 api의 서버 도메인을 환경변수로 교체
  src/apis/login.js
  src/components/InputBar/InputBar.jsx
  src/components/ReviewDownload/ReviewDownload.jsx
  src/dummy/data/user.js
  src/hooks/useComment.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
Labels: 🔧 Fix

#243 #242 [FEAT] 배너 이미지 조회 API 연결
  src/apis/banner.js
  src/apis/index.js
  src/components/Carousel/Carousel/Carousel.jsx
  src/components/Carousel/Slide/Slide.jsx
  src/components/Carousel/Slide/Slide.module.css
  src/pages/MainPage/MainPage.jsx
Labels: 📬 API

#244 [MERGE] 배너 연결 및 로그인 서버 도메인 환경변수로 교체
  src/apis/banner.js
  src/apis/index.js
  src/apis/login.js
  src/components/Carousel/Carousel/Carousel.jsx
  src/components/Carousel/Slide/Slide.jsx
  src/components/Carousel/Slide/Slide.module.css
  src/components/InputBar/InputBar.jsx
  src/components/ReviewDownload/ReviewDownload.jsx
  src/constants/index.js
  src/constants/route.js
  src/dummy/data/user.js
  src/hooks/useComment.jsx
  src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx
  src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
  src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
Labels: 🌏 Deploy

#247 #246 [FEAT] 구글 애드센스 연결
  public/index.html
  src/pages/AttendancePage/AttendancePage.jsx
Labels: ✨ Feature

#248 [MERGE] 구글 애드센스 연결
  public/index.html
  src/pages/AttendancePage/AttendancePage.jsx
Labels: 🌏 Deploy

#250 #221 게시글 / 시험후기 게시판에 role에 따른 접근 권한 설정
  src/ProtectedRoute.jsx
  src/components/WriteButton/WriteButton.module.css
  src/pages/PostPage/PostWritePage/PostWritePage.jsx
  src/route.js
Labels: ✨ Feature

#249 #245 [FEAT] axios 타이아웃 시간 전역으로 설정
  src/axios/index.js
Labels: ✨ Feature
