Repository snorose/snorose-front-react, pull requests merged in 2025-03, with the labels that each got.

#827 #826 [FIX] BackAppBar 히스토리가 비정상적으로 동작하는 문제 수정
  src/components/Search/Search.jsx
  src/pages/NoticeListPage/NoticeListPage.jsx
  src/pages/PostsPage/PostsPage.jsx
  src/pages/SearchPage/SearchPage.jsx
Labels: 🐞 BugFix

#833 #832 [CHORE] 명예의 전당 업데이트
  src/components/Accordion/Accordion.module.css
  src/constants/about.js
Labels: 🧹 Chore

#837 #836 [FEAT] 헤더 로고 클릭 시 홈페이지로 이동 기능 구현
  src/shared/component/layout/Header/Header.jsx
Labels: ✨ Feature

#845 #844 [CHORE] 팝업 공지글 게시 (250313)
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/home/component/PopUp/calendar-march.png
Labels: 🧹 Chore

#849 # 848 [FIX] 팝업 공지 좌우 스크롤 이슈 및 게시글 폰트가 비정상적으로 작은 문제 수정
  src/feature/home/component/PopUp/PopUp.module.css
  src/page/board/PostPage/PostPage.jsx
Labels: 🐞 BugFix

#850 [MERGE] 게시글 사이즈 오류 수정 및 팝업 스크롤 수정
  src/feature/home/component/PopUp/PopUp.module.css
  src/page/board/PostPage/PostPage.jsx
Labels: ❄️ Release

#840 #799 [FIX] 현재 게시판에 따른 일러스트 이미지 적용
  src/feature/my/component/MyPostList/MyPostList.jsx
  src/feature/my/component/MyPostList/MyPostList.module.css
  src/feature/my/constant/activity.js
Labels: 🎨 UI

#842 #841 [FIX] getDownloadedExamReviews으로 오탈자 수정
  src/apis/userInfo.js
  src/feature/my/constant/activity.js
Labels: 🧹 Chore

#853 #803 [DOCS] 스노로즈 컴포넌트 8개 스토리북 문서화
  .gitignore
  .storybook/index.css
  .storybook/preview.js
  src/stories/Accordion.stories.jsx
  src/stories/BoardBar.stories.jsx
  src/stories/Button.jsx
  src/stories/Button.stories.js
  src/stories/Configure.mdx
  src/stories/Header.jsx
  src/stories/Header.stories.js
  src/stories/Icon.mdx
  src/stories/Icon.stories.jsx
  src/stories/Page.jsx
  src/stories/Page.stories.js
  src/stories/PopUp.stories.jsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/layout/AppBar.stories.jsx
  src/stories/layout/BackAppBar.stories.jsx
  src/stories/layout/CloseAppBar.stories.jsx
  src/stories/layout/Footer.stories.jsx
  src/stories/layout/Header.stories.jsx
  src/stories/page.css
Labels: 📄 Docs

#856 #855 [CHORE] 팝업 공지글 게시 (250327)
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/home/component/PopUp/calendar-march.png
  src/feature/home/component/PopUp/event-innisfree.png
Labels: 🧹 Chore

#857 [MERGE] 팝업 공지 게시 (250327 ver.)
  .gitignore
  .storybook/index.css
  .storybook/preview.js
  src/apis/userInfo.js
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/home/component/PopUp/calendar-march.png
  src/feature/home/component/PopUp/event-innisfree.png
  src/feature/my/component/MyPostList/MyPostList.jsx
  src/feature/my/component/MyPostList/MyPostList.module.css
  src/feature/my/constant/activity.js
  src/stories/Accordion.stories.jsx
  src/stories/BoardBar.stories.jsx
  src/stories/Button.jsx
  src/stories/Button.stories.js
  src/stories/Configure.mdx
  src/stories/Header.jsx
  src/stories/Header.stories.js
  src/stories/Icon.mdx
  src/stories/Icon.stories.jsx
  src/stories/Page.jsx
  src/stories/Page.stories.js
  src/stories/PopUp.stories.jsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/layout/AppBar.stories.jsx
  src/stories/layout/BackAppBar.stories.jsx
  src/stories/layout/CloseAppBar.stories.jsx
  src/stories/layout/Footer.stories.jsx
  src/stories/layout/Header.stories.jsx
  src/stories/page.css
Labels: ❄️ Release
