Repository snorose/snorose-front-react, pull requests merged in 2025-07, with the labels that each got.

#1056 #1055 [SNO-125] 시험후기 작성 기간 연장 (~7.21 23:59)
  src/feature/exam/lib/CheckExamPeriodRoute.jsx
Labels: 🪄 Modify

#1061 [MERGE] iOS 기기 + 인앱 브라우저에서 사이트 화면이 로드되지 않는 이슈 해결 (250703 ver.)
  src/App.jsx
  src/feature/alert/lib/PushNotification.js
  src/feature/alert/lib/detectDeviceInfo.js
  src/feature/alert/lib/firebase-config.js
  src/feature/alert/lib/index.js
Labels: ❄️ Release

#1065 [MERGE] 0710 팝업 수정 (250710 ver.)
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/home/component/PopUp/calendar.jpg
  src/feature/home/component/PopUp/juneReport.png
Labels: ❄️ Release

#990 #986 [SNO-90] about snorose UI 변경
  src/feature/home/component/Accordion/Accordion.jsx
  src/feature/home/component/Accordion/Accordion.module.css
  src/feature/home/constant/about.js
  src/feature/home/data/HallOfFrameAdmins.json
  src/page/snorose/AboutPage/AboutPage.jsx
  src/page/snorose/AboutPage/AboutPage.module.css
Labels: 🎨 UI

#1069 #1068 [SNO-131] 모바일 Status Bar 색상 흰색으로 수정
  public/index.html
Labels: 🎨 UI

#1081 #1080 [SNO-134] 시험후기 게시판 z-index 수정
  src/feature/home/component/PopUp/PopUp.module.css
  src/shared/component/layout/AppBar/AppBar.module.css
  src/shared/component/layout/Sidebar/Sidebar.module.css
  src/shared/component/modal/Modal.module.css
Labels: 🎨 UI

#1051 #1050 [SNO-123] 서버 점검 페이지 UI 수정
  src/assets/illustrations/maintenanceConfig.svg
  src/assets/images/maintenanceConfig.svg
  src/feature/maintenance/hook/useMaintenance.jsx
  src/page/maintenance/MaintenancePage/MaintenancePage.jsx
  src/page/maintenance/MaintenancePage/MaintenancePage.module.css
  src/shared/lib/dateTime.js
Labels: 🎨 UI

#1083 [MERGE] 0718 팝업 수정 (250718 ver.)
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/home/component/PopUp/askUsAnything.jpg
Labels: ❄️ Release

#1089 #1088 [SNO-140] 홈 화면 하단 계좌번호 선택시 복붙 기능
  src/shared/component/layout/Footer/Footer.jsx
  src/shared/component/layout/Footer/Footer.module.css
  src/shared/constant/toast.js
Labels: ✨ Feature

#1072 #1070 [SNO-132] 댓글/공감/스크랩 UI 변경 (Ver.2)
  src/assets/icon.svg
  src/feature/board/component/PostBar/PostBar.jsx
  src/feature/board/component/PostBar/PostBar.module.css
  src/feature/comment/component/Comment/Comment.jsx
  src/feature/comment/component/Comment/Comment.module.css
  src/feature/comment/component/CommentInput/CommentInput.jsx
  src/feature/comment/component/NestedComment/NestedComment.jsx
  src/feature/comment/context/CommentContext.jsx
  src/page/board/PostPage/PostPage.jsx
  src/page/board/PostPage/PostPage.module.css
  src/style/variable.css
Labels: 🎨 UI

#1093 #1092 [SNO-143] footer 상수값으로 분리
  src/shared/component/layout/Footer/Footer.jsx
  src/shared/component/layout/Footer/Footer.module.css
  src/shared/constant/footerData.js
  src/shared/constant/index.js
Labels: 🛠️ Refactor
