Repository snorose/snorose-front-react, pull requests merged in 2025-09, with the labels that each got.

#1133 #1132 [FEAT] 0901 팝업
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/home/component/PopUp/august.jpeg
  src/feature/home/component/PopUp/september.jpg
Labels: 🍿 Pop-up

#1077 #1003 [SNO-84] 드롭다운 컴포넌트 디자인 변경
  src/assets/icon.svg
  src/feature/account/component/signUpStep/UserInfoStep/UserInfoStep.jsx
  src/feature/account/component/signUpStep/UserInfoStep/UserInfoStep.module.css
  src/feature/board/component/DropDownMenu/DropDownMenu.jsx
  src/feature/my/component/index.js
  src/page/board/WritePostPage/WritePostPage.jsx
  src/page/board/WritePostPage/WritePostPage.module.css
  src/page/user/EditProfilePage/EditProfilePage.jsx
  src/shared/component/CategoryFieldset/CategoryFieldset.jsx
  src/shared/component/CategoryFieldset/CategoryFieldset.module.css
  src/shared/component/Dropdown/Dropdown.jsx
  src/shared/component/Dropdown/Dropdown.module.css
  src/shared/component/dropdown/Dropdown/Dropdown.jsx
  src/shared/component/dropdown/Dropdown/Dropdown.module.css
  src/shared/component/dropdown/DropdownList/DropdownList.jsx
  src/shared/component/dropdown/DropdownList/DropdownList.module.css
  src/shared/component/dropdown/SelectedItem/SelectedItem.jsx
  src/shared/component/dropdown/SelectedItem/SelectedItem.module.css
  src/shared/component/index.js
Labels: 🎨 UI

#1121 #1118 [SNO-156] 댓글 등록 및 삭제 시 화면 깜빡거리는 이슈 해결
  src/feature/comment/hook/useComment.jsx
Labels: 🐞 BugFix

#1136 [MERGE] dev to main (250902 ver.)
  src/assets/icon.svg
  src/feature/account/component/signUpStep/AccountInfoStep/AccountInfoStep.jsx
  src/feature/account/component/signUpStep/AuthorizationStep/AuthorizationStep.jsx
  src/feature/account/component/signUpStep/UserInfoStep/UserInfoStep.jsx
  src/feature/account/component/signUpStep/UserInfoStep/UserInfoStep.module.css
  src/feature/board/component/DropDownMenu/DropDownMenu.jsx
  src/feature/board/component/DropDownMenu/DropDownMenu.module.css
  src/feature/comment/hook/useComment.jsx
  src/feature/exam/component/Filter/Filter.module.css
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/home/component/PopUp/PopUp.module.css
  src/feature/home/component/PopUp/august.jpeg
  src/feature/home/component/PopUp/september.jpg
  src/feature/my/component/CircleProfile/CircleProfile.module.css
  src/feature/my/component/TopOverlay/TopOverlay.module.css
  src/feature/my/component/index.js
  src/index.css
  src/page/board/WritePostPage/WritePostPage.jsx
  src/page/board/WritePostPage/WritePostPage.module.css
  src/page/user/ChangePwPage/ChangePwPage.jsx
  src/page/user/EditProfilePage/EditProfilePage.jsx
  src/page/user/MyPage/MyPage.module.css
  src/shared/component/CategoryFieldset/CategoryFieldset.jsx
  src/shared/component/CategoryFieldset/CategoryFieldset.module.css
  src/shared/component/Dropdown/Dropdown.jsx
  src/shared/component/Dropdown/Dropdown.module.css
  src/shared/component/PullToRefresh/PullToRefresh.module.css
  src/shared/component/button/WriteButton/WriteButton.module.css
  src/shared/component/dropdown/Dropdown/Dropdown.jsx
  src/shared/component/dropdown/Dropdown/Dropdown.module.css
  src/shared/component/dropdown/DropdownList/DropdownList.jsx
  src/shared/component/dropdown/DropdownList/DropdownList.module.css
  src/shared/component/dropdown/SelectedItem/SelectedItem.jsx
  src/shared/component/dropdown/SelectedItem/SelectedItem.module.css
  src/shared/component/index.js
  src/shared/component/input/Input/Input.module.css
  src/shared/component/input/Input/SpecialInput.module.css
  src/shared/component/layout/AppBar/AppBar.module.css
  src/shared/component/layout/BackAppBar/BackAppBar.module.css
  src/shared/component/layout/CloseAppBar/CloseAppBar.module.css
  src/shared/component/layout/Navbar/Navbar.module.css
  src/shared/component/layout/Sidebar/Sidebar.module.css
  src/shared/component/loading/FetchLoadingOverlay/FetchLoadingOverlay.module.css
  src/shared/component/modal/Modal.module.css
  src/style/variable.css
Labels: ❄️ Release

#1143 #1141 [SNO-180] 0908 팝업 수정 및 인증 페이지 내 워딩 변경
  src/feature/account/constant/verify.js
  src/feature/home/component/PopUp/PopUp.jsx
Labels: 🍿 Pop-up

#1145 #1144 [SNO-182] 단일 버튼 모달인 NoticeModal 컴포넌트 추가 및 인증 페이지에 적용
  src/ProtectedRoute.jsx
  src/shared/component/Modal/NoticeModal/NoticeModal.jsx
  src/shared/component/Modal/NoticeModal/NoticeModal.module.css
  src/shared/component/index.js
  src/shared/constant/modalText.js
Labels: 🐞 BugFix

#1148 #1147 [SNO-183] 인증페이지에서 스크롤 안되는 이슈 해결
  src/feature/account/component/snoroseVerifyStep/VerifyStep/VerifyStep.module.css
Labels: 🐞 BugFix

#1110 #854 [SNO-162] 첨부파일 - 이미지/동영상 업로드, 수정, 다운로드
  package-lock.json
  package.json
  src/apis/login.js
  src/apis/post.js
  src/assets/icon.svg
  src/feature/board/component/AttachmentBar/AttachmentBar.jsx
  src/feature/board/component/AttachmentBar/AttachmentBar.module.css
  src/feature/board/component/FullScreenAttachment/FullScreenAttachment.jsx
  src/feature/board/component/FullScreenAttachment/FullScreenAttachment.module.css
  src/feature/board/component/PostBar/PostBar.jsx
  src/feature/board/component/PostBar/PostBar.module.css
  src/feature/board/component/index.js
  src/page/board/EditPostPage/EditPostPage.jsx
  src/page/board/EditPostPage/EditPostPage.module.css
  src/page/board/PostPage/PostPage.jsx
  src/page/board/WritePostPage/WritePostPage.jsx
  src/page/board/WritePostPage/WritePostPage.module.css
  src/shared/component/AttachmentList/AttachmentList.jsx
  src/shared/component/AttachmentList/AttachmentList.module.css
  src/shared/component/AttachmentSwiper/AttachmentSwiper.jsx
  src/shared/component/AttachmentSwiper/AttachmentSwiper.module.css
  src/shared/component/Modal/ChoiceModal.jsx
  src/shared/component/Modal/Modal.module.css
  src/shared/component/index.js
  src/shared/component/modal/ChoiceModal.jsx
  src/shared/component/modal/ConfirmModal/ConfirmModal.jsx
  src/shared/component/modal/ConfirmModal/ConfirmModal.module.css
  src/shared/component/modal/Modal.module.css
  src/shared/constant/attachment.js
  src/shared/constant/icon.js
  src/shared/constant/index.js
  src/shared/constant/modalOptions.js
  src/shared/constant/modalText.js
  src/shared/constant/toast.js
  src/shared/lib/attachment.js
  src/shared/lib/index.js
Labels: ✨ Feature

#1162 #1161 [SNO-192] 상단 AppBar 높이 CSS 변수화 & 페이지 상단 여백 조정
  src/feature/account/component/snoroseVerifyStep/CompleteStep/CompleteStep.module.css
  src/feature/account/component/snoroseVerifyStep/TermsStep/TermsStep.module.css
  src/feature/account/component/snoroseVerifyStep/VerifyStep/VerifyStep.jsx
  src/feature/account/component/snoroseVerifyStep/VerifyStep/VerifyStep.module.css
  src/page/account/FindIdPage/FindIdPage.jsx
  src/page/account/FindIdPage/FindIdPage.module.css
  src/page/account/FindPwPage/FindPwPage.jsx
  src/page/account/FindPwPage/FindPwPage.module.css
  src/page/account/FoundIdPage/FoundIdPage.jsx
  src/page/account/FoundIdPage/FoundIdPage.module.css
  src/page/account/FoundPwPage/FoundPwPage.jsx
  src/page/account/FoundPwPage/FoundPwPage.module.css
  src/page/account/LoginPage/LoginPage.jsx
  src/page/account/NotFoundIdPage/NotFoundIdPage.jsx
  src/page/account/NotFoundIdPage/NotFoundIdPage.module.css
  src/page/account/NotFoundPwPage/NotFoundPwPage.jsx
  src/page/account/NotFoundPwPage/NotFoundPwPage.module.css
  src/page/account/SignUpFailure/SignUpFailurePage.jsx
  src/page/account/SignUpFailure/SignUpFailurePage.module.css
  src/page/account/SignUpPage/SignUpPage.jsx
  src/page/account/SignUpPage/SignUpPage.module.css
  src/page/account/SignUpSuccessPage/SignUpSuccessPage.jsx
  src/page/account/SignUpSuccessPage/SignUpSuccessPage.module.css
  src/page/account/SnoroseVerifyPage/SnoroseVerifyPage.jsx
  src/page/account/SnoroseVerifyPage/SnoroseVerifyPage.module.css
  src/page/board/EditPostPage/EditPostPage.module.css
  src/page/board/NoticeListPage/NoticeListPage.module.css
  src/page/board/PostListPage/PostListPage.module.css
  src/page/board/PostPage/PostPage.module.css
  src/page/board/WritePostPage/WritePostPage.module.css
  src/page/exam/EditExamReviewPage/EditExamReviewPage.module.css
  src/page/exam/ExamReviewListPage/ExamReviewListPage.module.css
  src/page/exam/ExamReviewPage/ExamReviewPage.module.css
  src/page/exam/WriteExamReviewPage/WriteExamReviewPage.module.css
  src/page/home/AttendancePage/AttendancePage.jsx
  src/page/search/SearchPage/SearchPage.module.css
  src/page/snorose/AboutPage/AboutPage.jsx
  src/page/snorose/AboutPage/AboutPage.module.css
  src/shared/component/layout/AppBar/AppBar.module.css
  src/shared/component/layout/BackAppBar/BackAppBar.module.css
  src/shared/component/layout/CloseAppBar/CloseAppBar.module.css
  src/shared/component/layout/Header/Header.module.css
  src/style/variable.css
Labels: 🎨 UI

#1164 #1163 [SNO-176] 청파제 기념 출석완료 토스트 메시지 문구 변경
  src/page/home/AttendancePage/AttendancePage.jsx
  src/shared/component/Toast/Toast.module.css
Labels: ✨ Feature

#1168 #1163 [SNO-176] 청파제 기념 출석완료 토스트 메시지 문구 변경
  src/page/home/AttendancePage/AttendancePage.jsx
Labels: ✨ Feature

#1169 [MERGE] dev to main (250916)
  src/page/home/AttendancePage/AttendancePage.jsx
  src/shared/component/Toast/Toast.module.css
Labels: ❄️ Release, 🍒 Cherry-pick

#1175 #1174 [SNO-199] 로고 단일 파일로 교체 및 관련 페이지 수정
  src/assets/images/blackCloudLogo.svg
  src/assets/images/cloudLogo.svg
  src/feature/board/component/PostBar/PostBar.jsx
  src/feature/board/component/PostBar/PostBar.module.css
  src/feature/comment/component/Comment/Comment.jsx
  src/feature/comment/component/Comment/Comment.module.css
  src/feature/comment/component/CommentInput/CommentInput.jsx
  src/feature/comment/component/CommentInput/CommentInput.module.css
  src/feature/comment/component/NestedComment/NestedComment.jsx
  src/feature/home/component/AccordionListItem/AccordionListItem.jsx
  src/feature/home/component/AccordionListItem/AccordionListItem.module.css
  src/page/board/BoardCategoryPage/BoardCategoryPage.jsx
  src/page/board/BoardCategoryPage/BoardCategoryPage.module.css
  src/page/board/EditPostPage/EditPostPage.jsx
  src/page/board/EditPostPage/EditPostPage.module.css
  src/page/board/PostPage/PostPage.jsx
  src/page/board/PostPage/PostPage.module.css
  src/page/board/WritePostPage/WritePostPage.jsx
  src/page/board/WritePostPage/WritePostPage.module.css
  src/page/exam/ExamReviewPage/ExamReviewPage.jsx
  src/page/exam/ExamReviewPage/ExamReviewPage.module.css
  src/shared/component/PullToRefresh/PullToRefresh.jsx
  src/shared/component/PullToRefresh/PullToRefresh.module.css
  src/shared/component/loading/FetchLoading/FetchLoading.jsx
  src/shared/component/loading/FetchLoading/FetchLoading.module.css
Labels: 🐞 BugFix

#1177 #1176 [SNO-200] 알림함 및 안 읽은 알림 개수 실시간 동기화
  src/App.jsx
  src/apis/alert.js
  src/feature/alert/lib/PushNotification.js
  src/shared/component/layout/Navbar/Navbar.jsx
  src/shared/constant/reactQuery.js
Labels: 🐞 BugFix

#1192 #1180 [SNO-202] 누락된 마케팅 정보 수신 동의 약관 페이지 구현
  src/feature/account/component/signUpStep/UserInfoStep/UserInfoStep.jsx
  src/feature/alert/component/SettingItem/SettingItem.jsx
  src/feature/alert/constant/index.js
  src/feature/alert/constant/terms.js
  src/page/account/CheckPrivacyTermPage/CheckPrivacyTermPage.jsx
  src/page/account/CheckPrivacyTermPage/CheckPrivacyTermPage.module.css
  src/page/alert/AlertSettingPage/AlertSettingPage.jsx
  src/page/alert/MarketingTermsPage/MarketingTermsPage.jsx
  src/page/alert/MarketingTermsPage/MarketingTermsPage.module.css
  src/page/alert/index.js
  src/router.js
Labels: 🐞 BugFix

#1193 #1184 [FIX] 푸시 알림 지원 여부 확인 로직을 보완하고, 알림 설정을 스마트폰 및 iOS PWA 환경에서만 허용하도록 수정
  src/App.jsx
  src/feature/alert/constant/error.js
  src/feature/alert/lib/PushNotification.js
  src/feature/alert/lib/environment.js
  src/page/alert/AlertSettingPage/AlertSettingPage.jsx
Labels: 🐞 BugFix

#1194 #1185 [SNO-201] 알림 설정 쿼리가 갱신되지 않는 문제 해결
  src/feature/alert/hook/notification.js
Labels: 🐞 BugFix

#1197 #1196 [SNO-204] 알림 설정 안내 UI 추가
  src/App.jsx
  src/page/alert/AlertSettingPage/AlertSettingPage.jsx
  src/page/alert/AlertSettingPage/AlertSettingPage.module.css
Labels: ✨ Feature

#1200 #1199 [SNO-207] 10월 캘린더 팝업
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/home/component/PopUp/october.png
  src/feature/home/component/PopUp/september.jpg
Labels: 🍿 Pop-up
