Repository snorose/snorose-front-react, pull requests merged in 2025-01, with the labels that each got.

#793 #791 [FEAT] 팝업 3일간 보지 않기
  src/components/PopUp/PopUp.jsx
  src/components/PopUp/PopUp.module.css
  src/hooks/usePopUp.jsx
  src/pages/MainPage/MainPage.jsx
  src/utils/date.js
Labels: ✨ Feature

#762 #760 [REFACTOR] 홈 화면의 API 로딩 및 에러 상태를 Suspense와 ErrorBoundary로 관리
  package-lock.json
  package.json
  src/apis/login.js
  src/axios/index.js
  src/components/Carousel/Carousel/Carousel.css
  src/components/Carousel/Carousel/Carousel.jsx
  src/components/Carousel/CarouselErrorFallback/CarouselErrorFallback.jsx
  src/components/Carousel/CarouselSkeleton/CarouselSkeleton.jsx
  src/components/Carousel/CarouselSkeleton/CarouselSkeleton.module.css
  src/components/Carousel/index.js
  src/components/ListHeader/ListHeader.module.css
  src/components/MainPageListItem/MainPageListItem.jsx
  src/components/MainPageListItem/MainPageListItem.module.css
  src/components/ServerErrorFallback/ServerErrorFallback.jsx
  src/components/ServerErrorFallback/ServerErrorFallback.module.css
  src/components/ServerErrorFallback/index.js
  src/components/ShimmerEffect/ShimmerEffect.jsx
  src/components/ShimmerEffect/ShimmerEffect.module.css
  src/components/ShimmerEffect/index.js
  src/components/index.js
  src/hooks/useAuth.js
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/MainPage.module.css
  src/pages/MainPage/components/HomeBesookt/HomeBesookt.jsx
  src/pages/MainPage/components/HomeBesookt/HomeBesookt.module.css
  src/pages/MainPage/components/HomeBesookt/HomeBesooktErrorFallback.jsx
  src/pages/MainPage/components/HomeBesookt/HomeBesooktErrorFallback.module.css
  src/pages/MainPage/components/HomeBesookt/HomeBesooktSkeleton.jsx
  src/pages/MainPage/components/HomeBesookt/HomeBesooktSkeleton.module.css
  src/pages/MainPage/components/HomeCard/HomeCard.jsx
  src/pages/MainPage/components/HomeCard/HomeCard.module.css
  src/pages/MainPage/components/HomeCard/HomeCardErrorFallback.jsx
  src/pages/MainPage/components/HomeCard/HomeCardSkeleton.jsx
  src/pages/MainPage/components/HomeCard/HomeCardSkeleton.module.css
  src/pages/MainPage/components/HomeCommunity/HomeCommunity.jsx
  src/pages/MainPage/components/HomeCommunity/HomeCommunity.module.css
  src/pages/MainPage/components/index.js
Labels: 🛠️ Refactor

#796 #795 [CHORE] 별모양 아이콘 추가하기
  src/assets/icon.svg
Labels: 🧹 Chore

#797 #794 [DOCS] Icon 컴포넌트 스토리북으로 문서화
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  craco.config.js
  jsconfig.json
  package-lock.json
  package.json
  src/components/Icon/Icon.jsx
  src/components/Icon/Icon.mdx
  src/components/Icon/Icon.stories.jsx
  src/constants/icon.js
  src/constants/index.js
  src/stories/Button.jsx
  src/stories/Button.stories.js
  src/stories/Configure.mdx
  src/stories/Header.jsx
  src/stories/Header.stories.js
  src/stories/Page.jsx
  src/stories/Page.stories.js
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: 📄 Docs, ⚙️ Setting

#788 #787 [FEAT] 사이드바에서 베숙트 메뉴 추가
  src/constants/menus.js
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
Labels: ✨ Feature

#798 #786 [FEAT] 게시판 날짜 표기 방식 변경
  src/components/PostBar/PostBar.jsx
  src/pages/PostPage/PostPage/PostPage.jsx
  src/utils/date.js
Labels: ✨ Feature
