Repository snorose/snorose-front-react, pull requests merged in 2025-04, with the labels that each got.

#863 #862 [CHORE] 팝업 공지 내리기
  src/page/home/MainPage/MainPage.jsx
Labels: 🎨 UI, 🧹 Chore

#864 [MERGE] dev to main
  src/page/home/MainPage/MainPage.jsx
Labels: ❄️ Release

#867 #866 [CHORE] 팝업 공지글 작성
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/home/component/PopUp/april-calendar.png
  src/feature/home/component/PopUp/event-innisfree.png
  src/page/home/MainPage/MainPage.jsx
Labels: 🧹 Chore

#868 [MERGE] 팝업 공지 게시 (250410 ver.)
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/home/component/PopUp/april-calendar.png
  src/feature/home/component/PopUp/event-innisfree.png
  src/page/home/MainPage/MainPage.jsx
Labels: ❄️ Release

#874 #873 [FIX] 모바일에서 focus시 화면 확대되지 않도록 meta에 속성값 설정
  public/index.html
Labels: 🎨 UI, 🧹 Chore

#877 [FIX] 수정 버튼 글자 크기
  src/shared/component/layout/CloseAppBar/CloseAppBar.module.css
Labels: 🧹 Chore

#878 [MERGE] dev to main
  public/index.html
  src/shared/component/layout/CloseAppBar/CloseAppBar.module.css
Labels: ❄️ Release

#875 #820 [FEAT] 공식 게시판 구현
  src/assets/icon.svg
  src/assets/images/adminBadge.svg
  src/assets/images/financeAudit-board-page.svg
  src/assets/images/graduationPreparation-board-page.svg
  src/assets/images/officialBadge.svg
  src/assets/images/studentCouncil-board-page.svg
  src/feature/board/component/BoardBar/BoardBar.module.css
  src/feature/board/component/PostBar/PostBar.jsx
  src/feature/board/component/PostBar/PostBar.module.css
  src/feature/comment/component/Comment/Comment.jsx
  src/feature/comment/component/Comment/Comment.module.css
  src/feature/comment/component/NestedComment/NestedComment.jsx
  src/feature/home/component/HomeBesookt/HomeBesookt.jsx
  src/feature/home/component/MainPageListItem/MainPageListItem.jsx
  src/feature/home/component/MainPageListItem/MainPageListItem.module.css
  src/feature/my/component/MyInfo/MyInfo.jsx
  src/feature/my/component/MyInfo/MyInfo.module.css
  src/page/board/BoardCategoryPage/BoardCategoryPage.jsx
  src/page/board/BoardCategoryPage/BoardCategoryPage.module.css
  src/page/board/EditPostPage/EditPostPage.jsx
  src/page/board/EditPostPage/EditPostPage.module.css
  src/page/board/NoticeListPage/NoticeListPage.jsx
  src/page/board/PostListPage/PostListPage.jsx
  src/page/board/PostPage/PostPage.jsx
  src/page/board/PostPage/PostPage.module.css
  src/page/board/WritePostPage/WritePostPage.jsx
  src/page/board/WritePostPage/WritePostPage.module.css
  src/router.js
  src/shared/component/Badge/Badge.jsx
  src/shared/component/Badge/index.js
  src/shared/component/index.js
  src/shared/constant/board.js
  src/shared/constant/menus.js
Labels: ✨ Feature

#881 #858 [FEAT] 스노로즈 1~2월 제언 일부 작업
  src/ProtectedRoute.jsx
  src/feature/exam/lib/CheckExamPeriodRoute.jsx
  src/page/exam/WriteExamReviewPage/WriteExamReviewPage.jsx
Labels: ✨ Feature

#870 #869 [CHORE] 팝업에서 3월 회계 내용만 삭제 (4/20까지만 게시 예정, 4/21에 merge 해주세요)
  src/feature/home/component/PopUp/PopUp.jsx
Labels: 🧹 Chore, 🙏 Next

#887 [MERGE] 공식게시판 및 제언 작업
  src/ProtectedRoute.jsx
  src/assets/icon.svg
  src/assets/images/adminBadge.svg
  src/assets/images/financeAudit-board-page.svg
  src/assets/images/graduationPreparation-board-page.svg
  src/assets/images/officialBadge.svg
  src/assets/images/studentCouncil-board-page.svg
  src/feature/board/component/BoardBar/BoardBar.module.css
  src/feature/board/component/PostBar/PostBar.jsx
  src/feature/board/component/PostBar/PostBar.module.css
  src/feature/comment/component/Comment/Comment.jsx
  src/feature/comment/component/Comment/Comment.module.css
  src/feature/comment/component/NestedComment/NestedComment.jsx
  src/feature/exam/lib/CheckExamPeriodRoute.jsx
  src/feature/home/component/HomeBesookt/HomeBesookt.jsx
  src/feature/home/component/MainPageListItem/MainPageListItem.jsx
  src/feature/home/component/MainPageListItem/MainPageListItem.module.css
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/my/component/MyInfo/MyInfo.jsx
  src/feature/my/component/MyInfo/MyInfo.module.css
  src/page/board/BoardCategoryPage/BoardCategoryPage.jsx
  src/page/board/BoardCategoryPage/BoardCategoryPage.module.css
  src/page/board/EditPostPage/EditPostPage.jsx
  src/page/board/EditPostPage/EditPostPage.module.css
  src/page/board/NoticeListPage/NoticeListPage.jsx
  src/page/board/PostListPage/PostListPage.jsx
  src/page/board/PostPage/PostPage.jsx
  src/page/board/PostPage/PostPage.module.css
  src/page/board/WritePostPage/WritePostPage.jsx
  src/page/board/WritePostPage/WritePostPage.module.css
  src/page/exam/WriteExamReviewPage/WriteExamReviewPage.jsx
  src/router.js
  src/shared/component/Badge/Badge.jsx
  src/shared/component/Badge/index.js
  src/shared/component/index.js
  src/shared/constant/board.js
  src/shared/constant/menus.js
Labels: ❄️ Release

#894 #893 [CHORE] 컴포넌트 클릭 시, 해당 파일로 바로 이동하도록 jsconfig.json 추가
  jsconfig.json
Labels: ⚙️ Setting

#898 #897 [CHORE] 팝업 내용 내에 기간이 중복으로 들어가 있는 이슈 해결
  src/feature/home/component/PopUp/PopUp.jsx
Labels: 🧹 Chore

#899 [MERGE] 팝업 공지 수정 (250424 ver.)
  jsconfig.json
  src/feature/home/component/MainPageListItem/MainPageListItem.jsx
  src/feature/home/component/PopUp/PopUp.jsx
Labels: ❄️ Release

#890 #884 [STYLE] 로그인/회원가입 일러스트 이미지 변경
  src/assets/icon.svg
  src/assets/images/emailSendIllustration.svg
  src/assets/images/taskCompleteIllustration.svg
  src/assets/images/taskFailedIllustration.svg
  src/feature/account/component/snoroseVerifyStep/CompleteStep/CompleteStep.jsx
  src/feature/account/component/snoroseVerifyStep/CompleteStep/CompleteStep.module.css
  src/page/account/FoundIdPage/FoundIdPage.jsx
  src/page/account/FoundIdPage/FoundIdPage.module.css
  src/page/account/FoundPwPage/FoundPwPage.jsx
  src/page/account/FoundPwPage/FoundPwPage.module.css
  src/page/account/NotFoundIdPage/NotFoundIdPage.jsx
  src/page/account/NotFoundIdPage/NotFoundIdPage.module.css
  src/page/account/NotFoundPwPage/NotFoundPwPage.jsx
  src/page/account/NotFoundPwPage/NotFoundPwPage.module.css
  src/page/account/SignUpFailure/SignUpFailurePage.jsx
  src/page/account/SignUpFailure/SignUpFailurePage.module.css
  src/page/account/SignUpSuccessPage/SignUpSuccessPage.jsx
  src/page/account/SignUpSuccessPage/SignUpSuccessPage.module.css
  src/pages/BoardPage/BoardListPage/BoardListPage.module.css
  src/pages/PostPage/PostPage/PostContent.module.css
  src/shared/constant/icon.js
Labels: 🎨 UI

#906 #905 [CHORE] 일부 팝업 내용 삭제 (4/27까지만 게시 예정, 4/28에 merge 해주세요)
  src/feature/home/component/PopUp/PopUp.jsx
Labels: 🧹 Chore, 🙏 Next

#896 #895 [STYLE] 게시판 카테고리 페이지 일러스트 변경(파란 계열로)
  src/assets/images/besookt-board-page.png
  src/assets/images/besookt-board-page.svg
  src/assets/images/financeAudit-board-page.svg
  src/assets/images/firstSnow-board-page.svg
  src/assets/images/graduationPreparation-board-page.svg
  src/assets/images/largeSnow-board-page.svg
  src/assets/images/permanentSnow-board-page.svg
  src/assets/images/studentCouncil-board-page.svg
  src/feature/board/component/BoardBar/BoardBar.jsx
  src/feature/board/component/BoardBar/BoardBar.module.css
  src/shared/constant/board.js
Labels: 🎨 UI

#909 #908 [CHORE] 시험후기 작성 기간 변경
  src/feature/exam/lib/CheckExamPeriodRoute.jsx
Labels: 🧹 Chore

#914 #913 [CHORE] 시험후기 작성 연도 옵션에 2025 추가
  src/feature/exam/constant/exam.js
Labels: 🧹 Chore

#915 [MERGE] 시험후기 작성 페이지에 2025 연도 옵션 추가
  src/feature/exam/constant/exam.js
Labels: ❄️ Release

#918 [FIX] 뷰포트 높이가 작아지는 경우 사이드바 내용이 화면 밖으로 넘치는 문제 해결
  src/shared/component/layout/Sidebar/Sidebar.module.css
Labels: 🐞 BugFix

#920 #919 [CHORE] 5월 팝업 공지 수정 및 사이드바에 '스노로즈 블로그'추가
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/home/component/PopUp/april-calendar.png
  src/feature/home/component/PopUp/calendar.jpg
  src/shared/constant/menus.js
Labels: ✨ Feature, 🧹 Chore

#921 [MERGE] 5월 팝업 공지 수정 (250430 ver.)
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/home/component/PopUp/april-calendar.png
  src/feature/home/component/PopUp/calendar.jpg
  src/shared/component/layout/Sidebar/Sidebar.module.css
  src/shared/constant/menus.js
Labels: ❄️ Release
