Repository snorose/snorose-front-react, pull requests merged in 2025-10, with the labels that each got.

#1208 #1207 [SNO-211] 팝업에 청파제 이벤트 포인트 지급 일정 관련 안내사항 추가
  src/feature/home/component/PopUp/PopUp.jsx
Labels: 🍿 Pop-up

#1209 [MERGE] dev to main (251004)
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/home/component/PopUp/october.png
  src/feature/home/component/PopUp/september.jpg
Labels: ❄️ Release, 🍒 Cherry-pick

#1210 #1178 [SNO-206] 알림 모두읽기 시 미확인 알림 개수가 실시간으로 동기화 되지 않는 이슈 해결
  src/feature/alert/hook/notification.js
Labels: 🐞 BugFix

#1224 #1211 [SNO-215] 푸시 알림 클릭 시 알림함으로 네비게이트
  public/firebase-messaging-sw.js
Labels: 🐞 BugFix

#1233 [MERGE] 게시글 생성 및 수정이 안 되는 버그 패치 (251006-2 ver.)
  src/apis/post.js
  src/page/board/WritePostPage/WritePostPage.jsx
Labels: ❄️ Release

#1235 #1234 [SNO-217] 게시글 수정 안 되는 이슈 패치
  src/apis/post.js
Labels: 🐞 BugFix

#1241 #1240 [SNO-179] 공지창과 검색창 컴포넌트 padding, 폰트사이즈, 아이콘 크기를 동일한 값으로 수정
  src/feature/search/component/Search/Search.module.css
  src/page/alert/AlertPage/AlertPage.module.css
  src/page/board/PostListPage/PostListPage.jsx
  src/page/board/PostListPage/PostListPage.module.css
  src/page/exam/ExamReviewListPage/ExamReviewListPage.jsx
  src/page/exam/ExamReviewListPage/ExamReviewListPage.module.css
Labels: 🎨 UI
