Repository snorose/snorose-front-react, pull requests merged in 2025-06, with the labels that each got.

#1024 #1023 [SNO-113] GrowthBookProvider 위치 수정
  src/App.jsx
  src/index.js
Labels: 🐞 BugFix

#1017 #1016 [SNO-89] 게시글 수정 API 스펙 변동으로 인한 400 에러 해결
  src/apis/post.js
Labels: 🐞 BugFix

#1037 #1036 [SNO-111] HomeBoardCard hover 케이스 적용
  src/feature/home/component/HomeBoardCard/HomeBoardCard.module.css
Labels: 🎨 UI

#1039 #1038 [SNO-112] 출석 상태에 따라 버튼 메시지 분기 (제언)
  src/apis/attendance.js
  src/apis/index.js
  src/apis/point.js
  src/page/home/AttendancePage/AttendancePage.jsx
  src/page/home/AttendancePage/AttendancePage.module.css
  src/router.js
  src/shared/component/loading/FetchLoadingOverlay/FetchLoadingOverlay.module.css
  src/shared/loader/attendance.js
  src/shared/loader/index.js
Labels: 🪄 Modify, 📝 Req

#1031 #926 [SNO-121] 시험후기 작성 페이지 undefined 참조 오류 해결
  src/feature/exam/lib/CheckExamPeriodRoute.jsx
  src/page/exam/WriteExamReviewPage/WriteExamReviewPage.jsx
Labels: 🐞 BugFix

#1042 [MERGE] dev to main (250611 ver.)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/modify-template.md
  .github/ISSUE_TEMPLATE/refactor-template.md
  .github/ISSUE_TEMPLATE/ui-update-template.md
  .github/pull_request_template.md
  src/ProtectedRoute.jsx
  src/apis/attendance.js
  src/apis/index.js
  src/apis/point.js
  src/feature/board/component/PostList/PostListSuspense.jsx
  src/feature/exam/lib/CheckExamPeriodRoute.jsx
  src/feature/home/component/HomeBoardCard/HomeBoardCard.module.css
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/home/component/PopUp/accountingReport.png
  src/feature/home/component/PopUp/june-calendar.png
  src/page/exam/WriteExamReviewPage/WriteExamReviewPage.jsx
  src/page/home/AttendancePage/AttendancePage.jsx
  src/page/home/AttendancePage/AttendancePage.module.css
  src/router.js
  src/shared/component/loading/FetchLoadingOverlay/FetchLoadingOverlay.module.css
  src/shared/loader/attendance.js
  src/shared/loader/index.js
Labels: ❄️ Release

#1005 #883 [SNO-46] 시험후기 API content, category 삭제
  src/page/exam/EditExamReviewPage/EditExamReviewPage.jsx
  src/page/exam/ExamReviewPage/ExamReviewPage.jsx
  src/page/exam/WriteExamReviewPage/WriteExamReviewPage.jsx
Labels: 🛠️ Refactor

#1030 #1029 [SNO-118] 좋아요수에 따른 리워드 변경(제언)
  src/feature/attendance/constant/point.js
Labels: ✨ Feature, 🙏 Next, 📝 Req

#1049 #1048 [FEAT] 250625 팝업 재수정
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/home/component/PopUp/accountingReport.png
  src/feature/home/component/PopUp/like-rewards.png
Labels: 🍿 Pop-up

#1046 [MERGE] dev to main (250624 ver.)
  src/feature/attendance/constant/point.js
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/home/component/PopUp/accountingReport.png
  src/feature/home/component/PopUp/like-rewards.png
  src/page/exam/EditExamReviewPage/EditExamReviewPage.jsx
  src/page/exam/ExamReviewPage/ExamReviewPage.jsx
  src/page/exam/WriteExamReviewPage/WriteExamReviewPage.jsx
Labels: ❄️ Release
