Repository snorose/snorose-front-react, pull requests merged in 2025-05, with the labels that each got.

#879 #803 [DOCS] 스노로즈 컴포넌트 9개 스토리북 문서화
  .storybook/index.css
  src/stories/ActionButton.stories.jsx
  src/stories/Calendar.stories.jsx
  src/stories/Carousel.stories.jsx
  src/stories/CarouselErrorFallback.stories.jsx
  src/stories/CarouselSkeleton.stories.jsx
  src/stories/HomeBoardCard.stories.jsx
  src/stories/HomeCard.stories.jsx
  src/stories/HomeCardErrorFallback.stories.jsx
  src/stories/HomeCardSkeleton.stories.jsx
Labels: 📄 Docs

#872 #843 [DOCS] storybook으로 문서화
  src/feature/exam/component/Filter/Filter.module.css
  src/feature/home/component/ListHeader/ListHeader.module.css
  src/feature/home/component/MainPageListItem/MainPageListItem.module.css
  src/shared/component/modal/ConfirmModal/ConfirmModal.module.css
  src/stories/ConfirmModal.stories.jsx
  src/stories/FetchLoading.stories.jsx
  src/stories/FetchLoadingOverlay.stories.jsx
  src/stories/Filter.stories.jsx
  src/stories/Input.stories.jsx
  src/stories/List.stories.jsx
  src/stories/ListHeader.stories.jsx
  src/stories/MainPageListItem.stories.jsx
  src/stories/MenuIcon.stories.jsx
  src/stories/NoticeBar.stories.jsx
  src/stories/PwInput.stories.jsx
  src/stories/SpecialInput.stories.jsx
  src/stories/Textarea.stories.jsx
  src/stories/layout/Navbar.stories.jsx
Labels: 📄 Docs

#900 #885 [STYLE] [마이페이지] - [내활동] 탭 내 일러스트 변경
  src/assets/illustrations/emailSendIllustration.svg
  src/assets/illustrations/index.js
  src/assets/illustrations/noCommentedPostsIllustration.svg
  src/assets/illustrations/noPostsIllustration.svg
  src/assets/illustrations/noScrapedPostsIllustration.svg
  src/assets/illustrations/taskCompleteIllustration.svg
  src/assets/illustrations/taskFailedIllustration.svg
  src/assets/images/EnlightenedWoman.svg
  src/assets/images/excitedWoman.svg
  src/assets/images/frustratedWoman.svg
  src/feature/my/component/MyPostList/MyPostList.jsx
  src/feature/my/constant/activity.js
  src/page/account/FoundIdPage/FoundIdPage.jsx
  src/page/account/FoundPwPage/FoundPwPage.jsx
  src/page/account/NotFoundIdPage/NotFoundIdPage.jsx
  src/page/account/NotFoundPwPage/NotFoundPwPage.jsx
  src/page/account/SignUpFailure/SignUpFailurePage.jsx
  src/page/account/SignUpSuccessPage/SignUpSuccessPage.jsx
Labels: 🎨 UI

#923 [SNO-41] 이슈 템플릿 및 PR 템플릿 수정 및 생성
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/chore-template.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactor-template.md
  .github/ISSUE_TEMPLATE/ui-update-template.md
  .github/pull_request_template.md
Labels: 🧹 Chore

#935 Revert "#919 [REMOVE] 5월 팝업 내 시험 후기 게시판 운영 내용 삭제"
  src/feature/home/component/PopUp/PopUp.jsx
Labels: 🐞 BugFix

#937 #936 [SNO-57] 5월 팝업에서 시험 후기 내용 삭제
  src/feature/home/component/PopUp/PopUp.jsx
Labels: 🧹 Chore

#944 #943 [SNO-62] 5월 달력 삭제 후 회계 보고 및 후원금 이벤트로 변경 (5/9 밤에 배포 예정)
  src/feature/home/component/PopUp/PopUp.jsx
  src/feature/home/component/PopUp/calendar.jpg
  src/feature/home/component/PopUp/financial-report.png
  src/feature/home/component/PopUp/fundraising-event.jpg
Labels: 🧹 Chore

#947 #943 [FIX] 충돌 해결
  src/shared/component/modal/ConfirmModal/ConfirmModal.module.css
  src/stories/BoardBar.stories.jsx
  src/stories/PopUp.stories.jsx
  src/stories/layout/AppBar.stories.jsx
  src/stories/layout/BackAppBar.stories.jsx
  src/stories/layout/CloseAppBar.stories.jsx
  src/stories/layout/Footer.stories.jsx
  src/stories/layout/Header.stories.jsx
Labels: 🐞 BugFix

#964 [SNO-69] #963 게시판 카테고리 페이지 폰트 사이즈 수정
  src/feature/board/component/BoardBar/BoardBar.module.css
  src/feature/search/component/Search/Search.module.css
  src/page/board/BoardCategoryPage/BoardCategoryPage.module.css
  src/shared/component/layout/Header/Header.module.css
Labels: 🎨 UI

#950 [SNO-66] #949 게시글 상세 페이지 - 폰트 크기 수정 + 디자인 변경(댓글/공감/스크랩)
  src/assets/icon.svg
  src/feature/comment/component/Comment/Comment.jsx
  src/feature/comment/component/Comment/Comment.module.css
  src/feature/comment/component/CommentInput/CommentInput.jsx
  src/feature/comment/component/CommentInput/CommentInput.module.css
  src/feature/comment/component/CommentList/CommentList.module.css
  src/feature/comment/component/NestedComment/NestedComment.jsx
  src/feature/comment/context/CommentContext.jsx
  src/page/board/PostPage/PostPage.jsx
  src/page/board/PostPage/PostPage.module.css
  src/style/variable.css
Labels: 🎨 UI, 🪄 Modify

#959 [SNO-64] #958 게시글 리스트, 공지글 리스트, 검색 리스트 - 폰트 크기 수정
  src/feature/board/component/NoticeBar/NoticeBar.jsx
  src/feature/board/component/NoticeBar/NoticeBar.module.css
  src/feature/board/component/PostBar/PostBar.jsx
  src/feature/board/component/PostBar/PostBar.module.css
  src/feature/search/component/Search/Search.module.css
  src/page/board/PostListPage/PostListPage.jsx
  src/page/board/PostListPage/PostListPage.module.css
  src/shared/component/button/WriteButton/WriteButton.module.css
  src/shared/component/layout/BackAppBar/BackAppBar.jsx
  src/shared/component/layout/BackAppBar/BackAppBar.module.css
Labels: 🎨 UI

#951 #941 [SNO-32] 아이디 기억하기 기능 구현 (2025 제언)
  src/assets/icon.svg
  src/page/account/LoginPage/LoginPage.jsx
  src/page/account/LoginPage/LoginPage.module.css
  src/shared/component/input/Input/Input.jsx
Labels: ✨ Feature

#954 #952 [SNO-61] 스크랩한 글 일러스트 변경
  src/feature/my/constant/activity.js
Labels: 🎨 UI

#957 #927 [SNO-42] 홈 페이지 및 인증 페이지의 폰트 사이즈 변경
  src/assets/icon.svg
  src/assets/images/completeVerification.svg
  src/assets/images/lock.svg
  src/feature/account/component/AuthInput/AuthInput.module.css
  src/feature/account/component/snoroseVerifyStep/CompleteStep/CompleteStep.jsx
  src/feature/account/component/snoroseVerifyStep/CompleteStep/CompleteStep.module.css
  src/feature/account/component/snoroseVerifyStep/TermsStep/TermsStep.jsx
  src/feature/account/component/snoroseVerifyStep/TermsStep/TermsStep.module.css
  src/feature/account/component/snoroseVerifyStep/VerifyStep/VerifyStep.jsx
  src/feature/account/component/snoroseVerifyStep/VerifyStep/VerifyStep.module.css
  src/feature/account/constant/verify.js
  src/feature/home/component/HomeBesookt/HomeBesookt.jsx
  src/feature/home/component/HomeBesookt/HomeBesooktErrorFallback.module.css
  src/feature/home/component/HomeBoardCard/HomeBoardCard.jsx
  src/feature/home/component/HomeBoardCard/HomeBoardCard.module.css
  src/feature/home/component/HomeCard/HomeCard.module.css
  src/feature/home/component/ListHeader/ListHeader.jsx
  src/feature/home/component/ListHeader/ListHeader.module.css
  src/feature/home/component/MainPageListItem/MainPageListItem.jsx
  src/feature/home/component/MainPageListItem/MainPageListItem.module.css
  src/feature/home/component/index.js
  src/index.css
  src/page/account/SnoroseVerifyPage/SnoroseVerifyPage.module.css
  src/page/home/MainPage/MainPage.module.css
  src/shared/component/button/PrimaryButton/PrimaryButton.module.css
  src/shared/component/input/PwInput/PwInput.module.css
  src/shared/component/layout/Footer/Footer.jsx
  src/shared/component/layout/Footer/Footer.module.css
  src/shared/component/layout/Header/Header.module.css
  src/shared/component/layout/Navbar/Navbar.module.css
  src/shared/component/layout/Sidebar/Sidebar.jsx
  src/shared/component/layout/Sidebar/Sidebar.module.css
  src/shared/constant/board.js
  src/shared/constant/icon.js
  src/shared/constant/menus.js
  src/stories/MainPageListItem.stories.jsx
  src/style/reset.css
Labels: 🎨 UI

#902 #900 [STYLE] 이용약관 내 UI 변경
  src/page/snorose/PolicyPage/PolicyPage.module.css
Labels: 🎨 UI, 🙏 Next

#904 #903 [STYLE] 계정 삭제 내 UI 변경
  .storybook/index.css
  src/page/user/DeleteAccountPage/DeleteAccountPage.jsx
  src/page/user/DeleteAccountPage/DeleteAccountPage.module.css
  src/shared/component/input/PwInput/PwInput.module.css
  src/shared/component/modal/ConfirmModal.module.css
  src/shared/component/modal/ConfirmModal/ConfirmModal.module.css
Labels: 🎨 UI

#969 #968 [SNO-76] 홈 베숙트에서 상세 페이지로 이동이 안 되는 문제 수정
  src/feature/home/component/HomeBesookt/HomeBesookt.jsx
Labels: 🐞 BugFix

#965 #886 [SNO-74] 마이페이지 및 하단 탭 메뉴 변경
  src/assets/backgrounds/snowyBackground.png
  src/assets/icon.svg
  src/assets/images/symbolWhite50.png
  src/assets/images/symbol_White.png
  src/feature/my/component/AccountTab/AccountTab.jsx
  src/feature/my/component/AccountTab/AccountTab.module.css
  src/feature/my/component/ActivityTab/ActivityTab.jsx
  src/feature/my/component/ActivityTab/ActivityTab.module.css
  src/feature/my/component/CircleProfile/CircleProfile.module.css
  src/feature/my/component/MyInfo/MyInfo.jsx
  src/feature/my/component/MyInfo/MyInfo.module.css
  src/feature/my/component/PolicyTab/PolicyTab.jsx
  src/feature/my/component/PolicyTab/PolicyTab.module.css
  src/feature/my/component/TopOverlay/TopOverlay.jsx
  src/feature/my/component/TopOverlay/TopOverlay.module.css
  src/page/account/LoginPage/LoginPage.module.css
  src/page/snorose/PolicyPage/PolicyPage.module.css
  src/page/user/MyPage/MyPage.module.css
  src/shared/component/layout/Navbar/Navbar.module.css
  src/shared/constant/menus.js
Labels: 🎨 UI

#956 #955 [SNO-33] 프로필 수정 및 비밀번호 변경 페이지 ui 변경
  src/assets/images/defaultProfile.svg
  src/feature/my/component/CategoryFieldset/CategoryFieldset.jsx
  src/feature/my/component/CategoryFieldset/CategoryFieldset.module.css
  src/feature/my/component/index.js
  src/page/user/ChangePwPage/ChangePwPage.jsx
  src/page/user/ChangePwPage/ChangePwPage.module.css
  src/page/user/EditProfilePage/EditProfilePage.jsx
  src/page/user/EditProfilePage/EditProfilePage.module.css
  src/shared/component/Dropdown/Dropdown.module.css
  src/shared/component/input/PwInput/PwInput.module.css
Labels: 🎨 UI

#970 #961 [SNO-71] font size 단위를 rem으로 변경
  src/style/variable.css
Labels: 🎨 UI

#912 #911 [CHORE] About 스노로즈 내 회원등급 뱃지 추가
  src/assets/icon.svg
  src/feature/home/component/AccordionListItem/AccordionListItem.jsx
  src/feature/home/component/AccordionListItem/AccordionListItem.module.css
  src/feature/home/constant/about.js
  src/page/snorose/AboutPage/AboutPage.jsx
  src/shared/constant/icon.js
Labels: 🧹 Chore

#977 #975 [SNO-87] 이슈/PR 템플릿 피드백 반영
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/chore-template.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactor-template.md
  .github/ISSUE_TEMPLATE/ui-update-template.md
  .github/pull_request_template.md
Labels: 🧹 Chore

#981 #980 [SNO-88] 게시글 상세 페이지 버튼 아이콘 누락 해결
  src/assets/icon.svg
Labels: 🐞 BugFix

#984 #941 [SNO-32] 아이디 기억하기 기능 구현 (2025 제언)
  src/page/account/LoginPage/LoginPage.jsx
  src/page/account/LoginPage/LoginPage.module.css
Labels: ✨ Feature

#985 [MERGE] 아이디 기억하기 기능 복구 (250517 ver.)
  src/page/account/LoginPage/LoginPage.jsx
  src/page/account/LoginPage/LoginPage.module.css
Labels: ❄️ Release

#988 #987 [SNO-93] 홈화면 내 공지와 출석체크 너비 수정
  src/feature/home/component/HomeCard/HomeCard.module.css
Labels: 🎨 UI

#997 #996 [SNO-101] PostPage에서 내가 쓴 게시물에 점 세 개 아이콘 안 뜨는 오류 해결
  src/assets/icon.svg
Labels: 🐞 BugFix, 🎨 UI

#1008 #1000 [SNO-105] 베숙트 일러스트 넣는 방식 변경
  src/assets/images/besookt-board-page.png
  src/assets/images/besookt-board-page.svg
  src/feature/board/component/BoardBar/BoardBar.jsx
  src/feature/board/component/BoardBar/BoardBar.module.css
  src/shared/constant/board.js
Labels: 🎨 UI
