Repository snorose/snorose-front-react, pull requests merged in 2025-02, with the labels that each got.

#808 #807 [CHORE] 팝업 공지 내리기
  src/pages/MainPage/MainPage.jsx
Labels: 🧹 Chore

#809 [MERGE] 팝업 공지 내리기
  src/assets/icon.svg
  src/pages/LoginPage/FindIdPage/FindIdPage.module.css
  src/pages/LoginPage/FoundIdPage/FoundIdPage.jsx
  src/pages/LoginPage/FoundIdPage/FoundIdPage.module.css
  src/pages/LoginPage/FoundPwPage/FoundPwPage.jsx
  src/pages/LoginPage/FoundPwPage/FoundPwPage.module.css
  src/pages/LoginPage/NotFoundIdPage/NotFoundIdPage.jsx
  src/pages/LoginPage/NotFoundIdPage/NotFoundIdPage.module.css
  src/pages/LoginPage/NotFoundPwPage/NotFoundPwPage.jsx
  src/pages/LoginPage/NotFoundPwPage/NotFoundPwPage.module.css
  src/pages/LoginPage/SignUpPage/SignUpPageStages/SignUpFailure/SignUpFailurePage.jsx
  src/pages/LoginPage/SignUpPage/SignUpPageStages/SignUpFailure/SignUpFailurePage.module.css
  src/pages/LoginPage/SignUpPage/SignUpSuccessPage/SignUpSuccessPage.jsx
  src/pages/LoginPage/SignUpPage/SignUpSuccessPage/SignUpSuccessPage.module.css
  src/pages/MainPage/MainPage.jsx
Labels: ❄️ Release

#811 #810 [CHORE] 전공 목록에 변경 및 신설 학과 추가
  src/constants/majors.js
Labels: 🧹 Chore

#812 [MERGE] 전공 목록에 변경 및 신설 학과 추가
  src/constants/majors.js
Labels: ❄️ Release

#814 #813 [FIX] 게시글 작성 페이지에서 공지글 토글 버튼이 노출되지 않는 문제 해결
  src/assets/icon.svg
  src/pages/PostPage/PostWritePage/PostWritePage.module.css
Labels: 🐞 BugFix

#818 #817 [CHORE] 팝업 공지글 게시(250217)
  src/components/PopUp/Component.jsx
  src/components/PopUp/Component.module.css
  src/components/PopUp/PopUp.jsx
  src/components/Route/CheckExamPeriodRoute.jsx
  src/pages/MainPage/MainPage.jsx
Labels: 🧹 Chore

#823 #822 [FIX] 시험후기 작성 페이지 접근 못하게 제어
  src/components/Route/CheckExamPeriodRoute.jsx
Labels: 🐞 BugFix

#824 [MERGE] 잘못된 시험후기 업로드 기간 수정
  src/components/Route/CheckExamPeriodRoute.jsx
Labels: ❄️ Release
